<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Lesson;
use App\Models\ProgrammingLanguage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HtmlCoursesAndLessonsSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $html = ProgrammingLanguage::where('slug', 'html')->firstOrFail();
            $oldCourses = Course::where('programming_language_id', $html->id)->get();
            $oldCourseIds = $oldCourses->pluck('id');
            $oldLessonIds = Lesson::whereIn('course_id', $oldCourseIds)->pluck('id');

            // These polymorphic tables do not have foreign keys, so clean only
            // references belonging to the HTML records before cascading deletes.
            DB::table('favorites')
                ->whereIn('favoritable_type', [Course::class, Lesson::class])
                ->whereIn('favoritable_id', $oldCourseIds->merge($oldLessonIds))
                ->delete();
            DB::table('notes')
                ->whereIn('notable_type', [Course::class, Lesson::class])
                ->whereIn('notable_id', $oldCourseIds->merge($oldLessonIds))
                ->delete();
            DB::table('content_translations')
                ->whereIn('translatable_type', [Course::class, Lesson::class])
                ->whereIn('translatable_id', $oldCourseIds->merge($oldLessonIds))
                ->delete();

            // Course and lesson foreign keys are cascade-on-delete, including
            // progress, history, quizzes, quiz attempts, and quiz children.
            $oldCourses->each->delete();

            foreach ($this->courses() as $courseData) {
                $course = Course::create([
                    'programming_language_id' => $html->id,
                    'title' => $courseData['title'],
                    'slug' => $courseData['slug'],
                    'description' => $courseData['description'],
                    'thumbnail' => null,
                    'level' => (string) $courseData['level'],
                    'estimated_duration' => (string) $courseData['estimated_duration'],
                ]);

                foreach ($courseData['lessons'] as $order => $lessonData) {
                    Lesson::create([
                        'course_id' => $course->id,
                        'title' => $lessonData['title'],
                        'slug' => $lessonData['slug'],
                        'description' => $lessonData['description'],
                        'content' => $this->content($lessonData),
                        'lesson_order' => $order + 1,
                        'estimated_minutes' => $lessonData['estimated_minutes'],
                    ]);
                }
            }
        });
    }

    private function content(array $lesson): string
    {
        $example = htmlspecialchars($lesson['example'], ENT_QUOTES, 'UTF-8');

        return '<h2>' . $lesson['title'] . '</h2>'
            . '<p>' . $lesson['intro'] . '</p>'
            . '<h3>Why it matters</h3><p>' . $lesson['why'] . '</p>'
            . '<h3>Key concepts</h3><ul>'
            . implode('', array_map(fn (string $item): string => '<li>' . $item . '</li>', $lesson['concepts']))
            . '</ul>'
            . '<h3>Practical example</h3><pre><code>' . $example . '</code></pre>'
            . '<h3>Common mistakes and notes</h3><ul>'
            . implode('', array_map(fn (string $item): string => '<li>' . $item . '</li>', $lesson['notes']))
            . '</ul>'
            . '<h3>Practice task</h3><p>' . $lesson['practice'] . '</p>';
    }

    private function lesson(
        string $title,
        string $slug,
        string $description,
        int $estimatedMinutes,
        string $intro,
        string $why,
        array $concepts,
        string $example,
        array $notes,
        string $practice
    ): array {
        return compact(
            'title', 'slug', 'description', 'estimatedMinutes', 'intro', 'why',
            'concepts', 'example', 'notes', 'practice'
        ) + ['estimated_minutes' => $estimatedMinutes];
    }

    private function courses(): array
    {
        $l = fn (...$args) => $this->lesson(...$args);

        return [
            [
                'title' => 'HTML Fundamentals',
                'slug' => 'html-fundamentals',
                'description' => 'Learn the core building blocks of the web. This beginner course teaches you how to structure web pages using HTML from scratch, including headings, paragraphs, links, images, lists, and basic page structure.',
                'level' => 1,
                'estimated_duration' => 6,
                'lessons' => [
                    $l('Introduction to HTML', 'introduction-to-html', 'Understand what HTML is and how browsers use it to structure web content.', 24, 'HTML is the markup language that gives a web document structure and meaning. It describes content such as headings, paragraphs, links, and images so a browser can present that content to a reader.', 'A strong HTML foundation makes later CSS and JavaScript work easier because those technologies build on a well-structured document.', ['HTML uses elements made from an opening tag, content, and usually a closing tag.', 'Elements describe content rather than visual styling.', 'Browsers parse HTML into a document tree called the DOM.'], '<h1>Welcome to my page</h1>\n<p>I am learning how the web is structured.</p>', ['HTML is not a programming language because it does not express algorithms.', 'Do not choose tags only because they make text look large or bold.', 'A page can render despite mistakes, but invalid structure makes maintenance and accessibility harder.'], 'Write a small page containing one heading, two paragraphs, and a link to a site you trust.'),
                    $l('HTML Document Structure', 'html-document-structure', 'Learn the required outer structure of a valid HTML document.', 28, 'Every complete HTML page has a predictable skeleton. The doctype identifies modern HTML, the html element contains the document, and head and body divide metadata from visible content.', 'Using the standard skeleton gives browsers consistent parsing behavior and provides a clear home for metadata, styles, scripts, and page content.', ['The doctype declaration should be the first line.', 'The head contains metadata such as the title and character encoding.', 'The body contains content that users read or interact with.'], '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Learning HTML</title>\n  </head>\n  <body>\n    <h1>My first document</h1>\n  </body>\n</html>', ['Forgetting lang makes language tools less reliable.', 'The title belongs in head, not as a visible heading in body.', 'Indentation does not change meaning, but it reveals nesting mistakes.'], 'Create a valid document skeleton and add a title, language declaration, heading, and introductory paragraph.'),
                    $l('Headings and Paragraphs', 'headings-and-paragraphs', 'Organize written content with headings and paragraphs.', 22, 'Headings communicate the hierarchy of a document, while paragraphs group related sentences. HTML provides six heading levels, from h1 through h6.', 'A logical heading outline helps readers scan a page and helps assistive technology navigate sections efficiently.', ['Use one clear page topic as the h1.', 'Use h2 for major sections and lower levels for nested subsections.', 'Use p for normal blocks of prose.'], '<h1>City Guide</h1>\n<h2>Museums</h2>\n<p>The city museum opens every morning except Monday.</p>\n<h3>Getting there</h3>\n<p>It is a short walk from the central station.</p>', ['Do not skip heading levels merely to change font size.', 'Do not put several unrelated sentences in one giant paragraph.', 'Do not use repeated br elements to create layout spacing.'], 'Outline a short article about a hobby with one h1, at least two h2 headings, and a paragraph under each section.'),
                    $l('Text Formatting', 'text-formatting', 'Use HTML elements that add meaning to emphasized, important, quoted, and marked text.', 25, 'HTML text elements can communicate emphasis, importance, quotations, and edits. Their value is semantic: they tell tools and readers how a phrase functions.', 'Meaningful text markup remains understandable when visual styles change and can be interpreted by assistive technology.', ['strong indicates importance and em indicates emphasis.', 'mark highlights text relevant to the current context.', 'small, del, ins, and blockquote describe specific text roles.'], '<p><strong>Required:</strong> Bring your notebook.</p>\n<p><em>Tip:</em> Read the instructions carefully.</p>\n<blockquote>Good structure supports every other layer of a web page.</blockquote>', ['Do not use b or i when strong or em better expresses the meaning.', 'Do not use formatting tags as a substitute for headings.', 'Quote sources accurately and identify them when attribution matters.'], 'Format a short announcement using strong for an important instruction, em for a note, and blockquote for a quotation.'),
                    $l('Links and Navigation', 'links-and-navigation', 'Create links and connect users to other pages and resources.', 27, 'The anchor element creates hyperlinks. Its href identifies the destination, and its text should tell users what they will reach.', 'Links are the basic navigation system of the web. Clear link text improves scanning, keyboard use, and screen-reader navigation.', ['Use relative URLs for pages within the same site.', 'Use absolute URLs for external destinations.', 'Use navigation landmarks to group primary page links.'], '<nav aria-label="Primary">\n  <a href="/index.html">Home</a>\n  <a href="/lessons.html">Lessons</a>\n</nav>\n<p><a href="https://developer.mozilla.org/">Read the MDN HTML guide</a></p>', ['Avoid link text such as click here because it hides the destination.', 'Use buttons for actions and links for navigation.', 'Be cautious with target="_blank" and explain when a new tab will open.'], 'Build a three-link navigation menu that connects a home page, lessons page, and contact page.'),
                    $l('Images', 'images', 'Add informative and decorative images with appropriate alternatives.', 25, 'The img element embeds an image resource. Its src points to the resource and alt describes the image when it cannot be seen.', 'Images can communicate information quickly, but without an appropriate alternative they exclude people using screen readers or text-only tools.', ['Use alt for the image purpose, not every visible detail.', 'Width and height can reserve space and communicate intrinsic dimensions.', 'Use figure and figcaption when an image needs a visible caption.'], '<figure>\n  <img src="mountain.jpg" alt="A trail leading toward a mountain at sunrise" width="640" height="360">\n  <figcaption>Sunrise on the north trail.</figcaption>\n</figure>', ['Do not leave alt out for meaningful images.', 'Use an empty alt attribute for purely decorative images.', 'Check file paths and provide sensible dimensions for layout stability.'], 'Add two images to a travel page, giving each a useful alt description and one a figure caption.'),
                    $l('Lists', 'lists', 'Represent groups of related items with unordered, ordered, and description lists.', 23, 'Lists express relationships between items. Unordered lists suit collections without sequence, ordered lists suit steps or rankings, and description lists pair terms with explanations.', 'Correct list structure improves scanning and gives assistive technology the number and relationship of items.', ['ul contains li items without an implied order.', 'ol communicates sequence or priority.', 'dl uses dt for a term and dd for its description.'], '<h2>Setup steps</h2>\n<ol>\n  <li>Choose a folder.</li>\n  <li>Create the document.</li>\n  <li>Open it in a browser.</li>\n</ol>\n<ul><li>Keyboard</li><li>Notebook</li></ul>', ['Do not use paragraphs with hyphens to imitate lists.', 'Only li elements should be direct children of ul or ol.', 'Choose ordered versus unordered based on meaning, not appearance.'], 'Create an ordered recipe list and an unordered list of ingredients, then check their nesting.'),
                    $l('Tables', 'tables', 'Present genuinely tabular data with rows, columns, and headings.', 30, 'Tables are designed for data whose meaning depends on relationships between rows and columns. A table should have a clear caption and header cells where appropriate.', 'Accessible table structure lets readers understand values when navigating by row or column rather than seeing the whole grid at once.', ['Use table, thead, tbody, tr, th, and td for tabular data.', 'Use scope to associate a header with its row or column.', 'Use caption to name the data set.'], '<table>\n  <caption>Weekly study hours</caption>\n  <thead><tr><th scope="col">Day</th><th scope="col">Hours</th></tr></thead>\n  <tbody><tr><th scope="row">Monday</th><td>2</td></tr></tbody>\n</table>', ['Do not use tables for page layout.', 'Do not leave header cells ambiguous when a table grows.', 'Keep cells concise and use a caption for context.'], 'Create a two-column table showing four days and study hours, with row and column headers.'),
                    $l('Div and Span', 'div-and-span', 'Understand generic grouping elements and when to prefer more meaningful elements.', 20, 'div and span are neutral containers. div groups block-level content while span groups a phrase within a line, but neither describes what the content means.', 'Generic containers are useful for styling hooks and small structural groupings when no semantic element fits.', ['div creates a block-level grouping in normal flow.', 'span groups inline content.', 'A class or id can give a generic container a purpose for CSS or scripting.'], '<div class="profile-card">\n  <h2>Sam Lee</h2>\n  <p>Learning <span class="topic">HTML</span> fundamentals.</p>\n</div>', ['Do not replace article, nav, or main with div when their meaning applies.', 'Avoid deeply nesting generic containers without a reason.', 'A class names a reusable category; an id should identify one unique element.'], 'Mark up a profile card and use one span to emphasize a phrase without changing its meaning.'),
                    $l('Building Your First HTML Page', 'building-your-first-html-page', 'Combine foundational elements to build a complete small HTML page.', 35, 'A useful first page combines document structure, headings, paragraphs, links, an image, and lists into a coherent experience.', 'Building a complete page reveals how individual elements cooperate and gives you a foundation for later CSS styling.', ['Start with a valid document skeleton.', 'Group related information with headings and sections.', 'Review links, images, lists, and text for meaning and accessibility.'], '<!doctype html>\n<html lang="en">\n  <head><meta charset="utf-8"><title>About Alex</title></head>\n  <body>\n    <h1>About Alex</h1>\n    <p>I am learning to build for the web.</p>\n    <h2>Interests</h2>\n    <ul><li>Design</li><li>Reading</li></ul>\n  </body>\n</html>', ['Build structure before worrying about visual polish.', 'Validate nesting and make every meaningful image and link understandable.', 'Keep the first page focused instead of adding unrelated sections.'], 'Build a personal introduction page with a title, two sections, a list, an image, and a link to a favorite resource.'),
                ],
            ],
            [
                'title' => 'Semantic HTML & Accessibility',
                'slug' => 'semantic-html-accessibility',
                'description' => 'Master modern semantic HTML elements and learn how to make your websites accessible to everyone. This course covers proper use of semantic tags, ARIA attributes, and accessibility best practices.',
                'level' => 2,
                'estimated_duration' => 5,
                'lessons' => [
                    $l('Introduction to Semantic HTML', 'introduction-to-semantic-html', 'Learn why semantic elements are preferable to anonymous containers.', 24, 'Semantic HTML uses elements whose names describe the role of their content. Elements such as article, nav, and footer provide information about the document beyond visual appearance.', 'Semantic structure improves accessibility, search understanding, and maintainability because different tools can recognize page regions.', ['Semantic elements communicate purpose.', 'A semantic element still needs appropriate content and heading structure.', 'Visual layout and semantic meaning are related but not identical.'], '<header><h1>Local Garden Club</h1></header>\n<main><article><h2>Spring planting</h2><p>Prepare the soil before planting.</p></article></main>', ['Do not choose a semantic element simply because its default browser style looks useful.', 'Use one element for its intended role rather than stacking redundant landmarks.', 'Check the resulting outline and reading order.'], 'Take a page made mostly of div elements and identify three places where semantic elements would clarify the structure.'),
                    $l('Header, Nav and Footer', 'header-nav-and-footer', 'Build reusable page regions with header, nav, and footer.', 23, 'header introduces a page or section, nav groups important navigation links, and footer contains closing information for a page or section.', 'These landmarks let keyboard and assistive-technology users move quickly between major regions.', ['A page can have more than one header or footer when sections need them.', 'Use nav for significant groups of navigation links.', 'A footer can contain related links, author details, or legal information.'], '<header><h1>Recipe Journal</h1><nav aria-label="Main navigation"><a href="/recipes">Recipes</a><a href="/about">About</a></nav></header>\n<footer><p>Updated 2026</p></footer>', ['Do not wrap every group of links in nav.', 'A header is not automatically the page title unless you include one.', 'Give multiple nav landmarks distinct labels.'], 'Sketch the landmark structure for a small site with a brand header, primary navigation, and footer links.'),
                    $l('Main, Section and Article', 'main-section-and-article', 'Distinguish the page’s main content, thematic sections, and self-contained articles.', 27, 'main identifies the dominant content of a document. section groups a theme and usually has a heading. article represents content that could stand on its own or be reused elsewhere.', 'Choosing the right container makes long pages easier to navigate and helps content retain meaning when syndicated or restyled.', ['There should normally be one main element per document.', 'A section should answer what theme its heading introduces.', 'An article should make sense independently of surrounding content.'], '<main>\n  <section><h2>Latest news</h2><article><h3>Community garden opens</h3><p>Neighbors planted the first beds.</p></article></section>\n</main>', ['Do not use section as a generic spacing wrapper.', 'Do not put unrelated cards in one article unless they form one item.', 'Headings make section boundaries understandable.'], 'Classify five pieces of page content as main, section, or article and explain each choice.'),
                    $l('Aside and Figure', 'aside-and-figure', 'Use aside for related content and figure for self-contained media or illustrations.', 22, 'aside contains content related to the surrounding content but not part of its primary flow. figure groups media or other referenced content with an optional figcaption.', 'These elements preserve the relationship between supporting material and the content it supports.', ['aside can contain related links, tips, or advertisements.', 'figure can contain an image, code sample, chart, or quotation.', 'figcaption explains the figure’s context.'], '<article><h2>Map reading</h2><p>Contour lines show elevation.</p><aside><h3>Quick tip</h3><p>Read the legend first.</p></aside><figure><img src="map.png" alt="Contour map of a valley"><figcaption>Contour lines around the valley.</figcaption></figure></article>', ['Do not use aside for content that is essential to the main explanation.', 'A figure does not have to contain an image.', 'Write captions that add context rather than repeating alt text.'], 'Add a related tip and a labeled diagram to an article, then decide whether each belongs in aside or figure.'),
                    $l('Semantic Text Elements', 'semantic-text-elements', 'Use inline elements such as time, abbr, cite, and code to express meaning precisely.', 25, 'Semantic inline elements identify special kinds of text. They help readers and tools distinguish dates, abbreviations, citations, and computer-related terms.', 'Precise inline meaning supports translation, accessibility, search, and future styling without requiring visual clues.', ['time can expose a machine-readable datetime value.', 'abbr can provide the expanded form of an abbreviation.', 'code, kbd, samp, and var describe computing text.'], '<p>The workshop begins at <time datetime="2026-10-12T09:00">October 12 at 9 AM</time>.</p>\n<p>Press <kbd>Ctrl</kbd> + <kbd>S</kbd> to save.</p>\n<p><abbr title="HyperText Markup Language">HTML</abbr> uses <code>elements</code>.</p>', ['Use title on abbr when readers may not know the abbreviation.', 'Do not use code for every technical word if it is not code.', 'Use datetime values that machines can parse.'], 'Rewrite a short event notice using time, abbr, cite, and kbd where their meanings fit.'),
                    $l('Accessibility Fundamentals', 'accessibility-fundamentals', 'Understand the core accessibility habits that should guide every HTML page.', 30, 'Accessibility means people with different abilities and technologies can perceive, operate, understand, and navigate a page. Good HTML provides a foundation before any extra tooling is added.', 'Accessible pages serve more people and are usually easier for everyone to use, including keyboard users and people on small screens.', ['Use semantic structure and a logical reading order.', 'Ensure interactive controls are keyboard reachable and visibly focused.', 'Provide text alternatives, labels, and sufficient context.'], '<main><h1>Course schedule</h1><a href="/schedule">View the full schedule</a><form><label for="email">Email address</label><input id="email" name="email" type="email"></form></main>', ['Do not remove focus outlines without providing a clear replacement.', 'Do not rely on color alone to communicate state.', 'Test with keyboard navigation and zoom, not only a mouse.'], 'Audit one existing page for heading order, keyboard access, image alternatives, and form labels.'),
                    $l('ARIA Attributes', 'aria-attributes', 'Use ARIA carefully to describe custom or dynamic interfaces when native HTML is insufficient.', 30, 'ARIA adds roles, states, and properties that communicate information to assistive technology. Native HTML should be preferred whenever it already provides the needed behavior.', 'Correct ARIA can clarify custom widgets, but incorrect ARIA can make a simple native control harder to use.', ['Use aria-label or aria-labelledby to name an otherwise unnamed control.', 'Use aria-expanded and aria-controls for expandable regions.', 'ARIA changes what tools perceive, not what an element can do by itself.'], '<button type="button" aria-expanded="false" aria-controls="details">Show details</button>\n<div id="details" hidden><p>Additional information.</p></div>', ['Do not add a button role to a native button.', 'A clickable div with a role still needs keyboard behavior and state management.', 'Keep ARIA state synchronized with the visible interface.'], 'Describe the ARIA state and relationship needed for a collapsible help panel before implementing it.'),
                    $l('Accessible Links and Images', 'accessible-links-and-images', 'Write link text and image alternatives that communicate purpose and context.', 24, 'A link should make sense when read by itself, and an image alternative should convey the image’s purpose in the current context.', 'Screen-reader users often navigate lists of links or images without reading the surrounding paragraph.', ['Name the destination in link text.', 'Use concise alt text for informative images.', 'Use empty alt for decorative images that should be ignored.'], '<p>Compare plans in the <a href="/pricing">pricing guide</a>.</p>\n<img src="chart.png" alt="Bar chart showing visits rising from January to March">', ['Do not repeat nearby visible text unnecessarily in alt.', 'Do not use a file name as link text.', 'A linked image needs alternative text that describes the link destination.'], 'Improve five vague links and three image alt values so each remains clear when isolated.'),
                    $l('Accessible Forms', 'accessible-forms', 'Connect labels, instructions, errors, and grouping elements to form controls.', 29, 'Accessible forms give every control a visible or programmatic label and explain required formats. fieldset and legend group related controls such as radio buttons.', 'Clear forms reduce errors and allow assistive technologies to announce the information needed at each control.', ['Use label for with a matching input id.', 'Use required and appropriate input types to express constraints.', 'Use fieldset and legend for related choices.'], '<form><fieldset><legend>Contact preference</legend><label><input type="radio" name="preference" value="email"> Email</label><label><input type="radio" name="preference" value="phone"> Phone</label></fieldset><label for="message">Message</label><textarea id="message" name="message" required></textarea></form>', ['Placeholder text is not a replacement for a label.', 'Do not make required fields identifiable only by color.', 'Associate error text with the field and explain how to correct it.'], 'Design the accessible markup for a sign-up form with name, email, preference, and message fields.'),
                    $l('Building an Accessible Page', 'building-an-accessible-page', 'Combine semantic landmarks, headings, alternatives, links, and form labels into one accessible page.', 35, 'An accessible page is the result of many small decisions: meaningful regions, readable order, keyboard-friendly controls, and clear content alternatives.', 'Practicing the complete structure helps accessibility become part of normal HTML work instead of a late repair step.', ['Start with landmarks and a logical heading outline.', 'Check every image, link, and form control for a useful name.', 'Use native controls before adding custom ARIA behavior.'], '<header><nav aria-label="Primary"><a href="/">Home</a><a href="/contact">Contact</a></nav></header>\n<main><h1>Community workshop</h1><section><h2>Register</h2><form><label for="name">Name</label><input id="name" name="name" required></form></section></main>\n<footer><p>Community Learning Center</p></footer>', ['Accessibility is not a single attribute or automated score.', 'Keep the reading order aligned with the visual order.', 'Test headings, focus, labels, and alternatives with real interaction.'], 'Create a one-page workshop site and perform a keyboard-only review from header to footer.'),
                ],
            ],
            [
                'title' => 'HTML Forms & Validation',
                'slug' => 'html-forms-validation',
                'description' => 'Learn how to create powerful and user-friendly forms using HTML. This course covers all input types, form attributes, and built-in HTML5 validation techniques.',
                'level' => 2,
                'estimated_duration' => 5,
                'lessons' => [
                    $l('Introduction to HTML Forms', 'introduction-to-html-forms', 'Understand how forms collect user input and submit it for processing.', 22, 'A form groups controls that collect information. The browser can package named values and submit them to a URL using a method such as get or post.', 'Forms connect the user interface to a server or client-side process, so clear structure and names are essential.', ['form defines the submission boundary.', 'Controls need name attributes to contribute submitted values.', 'action and method describe where and how data is sent.'], '<form action="/signup" method="post"><label for="name">Name</label><input id="name" name="name"><button type="submit">Create account</button></form>', ['A control without name usually is not submitted.', 'Do not use a form as a generic container for unrelated content.', 'The server must validate submitted data even when the browser validates it.'], 'Draw the data flow for a contact form from a user’s input to the server endpoint.'),
                    $l('Form and Input Elements', 'form-and-input-elements', 'Choose appropriate controls and connect them to labels.', 25, 'HTML offers input, button, select, textarea, and several grouping elements. The control type should match the kind of data a user needs to provide.', 'The right control improves keyboard behavior, mobile keyboards, validation, and the clarity of the interaction.', ['Use label for and id to make the relationship explicit.', 'Use button type to distinguish submit, reset, and ordinary buttons.', 'Use fieldset and legend for related controls.'], '<form><label for="search">Search courses</label><input id="search" name="search" type="search"><button type="submit">Search</button></form>', ['Do not use divs to imitate controls when a native control exists.', 'Do not omit a name from data that must be submitted.', 'Keep labels visible when they provide necessary context.'], 'Choose controls for a survey containing a name, rating, topic selection, and comments field.'),
                    $l('Text and Password Inputs', 'text-and-password-inputs', 'Collect ordinary text and secret values with text and password inputs.', 20, 'Text inputs collect short single-line values. Password inputs hide characters visually, but they do not encrypt data by themselves.', 'Correct input types give users familiar behavior and allow browsers and password managers to help.', ['Use autocomplete hints when a browser can safely help.', 'Use minlength or maxlength when the data has clear boundaries.', 'A password field should be submitted over a secure connection.'], '<label for="username">Username</label><input id="username" name="username" type="text" autocomplete="username">\n<label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password">', ['Do not treat maxlength as security validation.', 'Never log passwords or place them in query strings.', 'Explain password requirements before the user submits.'], 'Design the markup for a login form and choose autocomplete values for its two controls.'),
                    $l('Email, URL and Telephone Inputs', 'email-url-and-telephone-inputs', 'Use specialized controls for email addresses, URLs, and telephone numbers.', 23, 'The email, url, and tel types communicate the expected kind of text. Browsers can offer basic validation and device-specific keyboards.', 'Specialized types reduce typing friction and catch obvious mistakes before data is sent.', ['type=email supports one or multiple addresses depending on the multiple attribute.', 'type=url expects a URL-like value.', 'type=tel preserves phone formatting rather than imposing numeric arithmetic.'], '<label for="email">Email</label><input id="email" name="email" type="email" required>\n<label for="site">Website</label><input id="site" name="site" type="url">\n<label for="phone">Phone</label><input id="phone" name="phone" type="tel">', ['Browser validity is not a complete business rule.', 'Do not use number for phone numbers because leading symbols and formatting matter.', 'Tell users which URL format the application accepts.'], 'Create a contact form using all three types and add labels plus appropriate required choices.'),
                    $l('Number, Range and Date Inputs', 'number-range-and-date-inputs', 'Collect numeric quantities, bounded choices, and dates with suitable input types.', 27, 'Number is for quantities that can be incremented, range is for a bounded value where exact text entry is less important, and date represents a calendar date.', 'These controls provide useful keyboard, validation, and mobile interaction behavior when the data really matches the type.', ['min, max, and step describe numeric constraints.', 'range usually needs a nearby output or text explanation.', 'Date values are submitted in a machine-readable format.'], '<label for="guests">Guests</label><input id="guests" name="guests" type="number" min="1" max="12" step="1">\n<label for="date">Arrival date</label><input id="date" name="date" type="date" required>', ['Do not use range when users need an exact visible value without another output.', 'Date picker appearance varies across browsers.', 'Validate numeric limits again on the server.'], 'Choose controls and constraints for a booking form with guests, price range, and arrival date.'),
                    $l('Radio Buttons and Checkboxes', 'radio-buttons-and-checkboxes', 'Represent one choice, multiple choices, and boolean preferences.', 23, 'Radio buttons in one named group allow one selection. Checkboxes allow independent selections and can represent a yes-or-no preference.', 'The distinction affects what users can choose and how the submitted data is interpreted.', ['Radio buttons that belong together share a name.', 'Each checkbox should have a useful label.', 'Use checked only when a choice is selected by default for a clear reason.'], '<fieldset><legend>Plan</legend><label><input type="radio" name="plan" value="starter" checked> Starter</label><label><input type="radio" name="plan" value="team"> Team</label></fieldset>\n<label><input type="checkbox" name="updates" value="yes"> Send updates</label>', ['Do not use several differently named radios for one exclusive choice.', 'A missing checkbox often means false rather than a submitted false value.', 'Do not preselect sensitive consent without a clear user action.'], 'Build a preference form with one exclusive plan choice and two independent notification choices.'),
                    $l('Select, Textarea and Datalist', 'select-textarea-and-datalist', 'Offer fixed choices, longer text, and suggestions for typed values.', 26, 'select works well for a known set of options, textarea collects multi-line text, and datalist provides suggestions while still allowing a typed value.', 'Matching the control to the choice set helps users understand whether they may choose one, many, or any value.', ['Use option values that are stable for submitted data.', 'Set rows and cols as useful starting dimensions for textarea.', 'Associate datalist with an input using the list attribute.'], '<label for="topic">Topic</label><select id="topic" name="topic"><option value="html">HTML</option><option value="css">CSS</option></select>\n<label for="message">Message</label><textarea id="message" name="message" rows="5"></textarea>\n<label for="browser">Browser</label><input id="browser" name="browser" list="browsers"><datalist id="browsers"><option value="Chrome"><option value="Firefox"></datalist>', ['Do not use placeholder options as valid submitted values.', 'Datalist is suggestions, not a replacement for server-side validation.', 'Long instructions belong outside the control and should be associated when needed.'], 'Design a feedback form with a topic select, message textarea, and browser datalist.'),
                    $l('Form Attributes', 'form-attributes', 'Control submission behavior with important form and control attributes.', 28, 'Form attributes influence destination, method, encoding, autocomplete, and whether the browser validates before submission.', 'Knowing these attributes helps forms work with real endpoints and file uploads without relying on accidental browser defaults.', ['method=get is visible and useful for searches; post is common for changes.', 'enctype multipart/form-data is required for file uploads.', 'novalidate and formnovalidate should be deliberate exceptions.'], '<form action="/upload" method="post" enctype="multipart/form-data" autocomplete="on"><label for="file">Profile image</label><input id="file" name="file" type="file" accept="image/*"><button type="submit">Upload</button></form>', ['Do not put sensitive values in a GET query string.', 'accept is a hint, not a security filter.', 'Never disable validation just to hide a confusing form design.'], 'Choose action, method, and encoding for search, sign-up, and file-upload scenarios.'),
                    $l('HTML5 Validation', 'html5-validation', 'Use built-in constraints to give immediate feedback on common input errors.', 30, 'HTML validation can check required values, patterns, lengths, ranges, and type-specific formats before a form submits.', 'Built-in validation provides fast feedback, but it must complement server-side validation rather than replace it.', ['required prevents empty submission.', 'pattern, minlength, maxlength, min, max, and step express constraints.', 'The browser exposes validity states and messages to the user.'], '<label for="code">Invite code</label><input id="code" name="code" pattern="[A-Z]{3}-[0-9]{4}" title="Use three capitals, a dash, and four numbers" required>\n<label for="age">Age</label><input id="age" name="age" type="number" min="13" max="120" required>', ['Patterns validate the whole value in browser constraint validation.', 'Do not rely on title alone to explain complicated requirements.', 'Server validation must repeat rules because requests can bypass the browser.'], 'Add validation constraints to a registration form and list the feedback a user should receive for each failure.'),
                    $l('Building a Complete Form', 'building-a-complete-form', 'Build a coherent, labeled, validated form that combines the course concepts.', 36, 'A complete form starts with a purpose, groups related controls, uses matching labels and names, and gives users clear constraints and feedback.', 'A realistic form project turns individual elements into a reliable user flow that can be handed to a backend.', ['Plan the data before choosing controls.', 'Use semantic groups and a logical tab order.', 'Combine browser validation with clear instructions and server validation.'], '<form action="/workshops/register" method="post"><h2>Workshop registration</h2><label for="full-name">Full name</label><input id="full-name" name="full_name" required>\n<label for="email">Email</label><input id="email" name="email" type="email" required>\n<label for="level">Experience</label><select id="level" name="level"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option></select>\n<button type="submit">Register</button></form>', ['Do not collect information the form does not need.', 'Check error messages with keyboard and screen-reader-friendly labels.', 'Keep the form usable on a narrow screen without relying on hover.'], 'Plan and mark up a workshop registration form with at least eight purposeful controls and a validation checklist.'),
                ],
            ],
            [
                'title' => 'HTML5 Multimedia & APIs',
                'slug' => 'html5-multimedia-apis',
                'description' => 'Explore HTML5 multimedia features including audio, video, canvas, and basic browser APIs. Learn how to embed and control media content effectively.',
                'level' => 3,
                'estimated_duration' => 6,
                'lessons' => [
                    $l('Introduction to HTML5 Multimedia', 'introduction-to-html5-multimedia', 'Understand native media elements and the responsibilities of an accessible media experience.', 24, 'Modern HTML can embed audio and video without requiring a browser plugin. Media elements expose controls, sources, captions, and fallback content.', 'Native elements provide predictable semantics and browser integration while leaving room for progressive enhancement.', ['audio and video are media containers.', 'source can provide alternate formats.', 'Captions and transcripts make media more inclusive.'], '<video controls width="640" poster="preview.jpg"><source src="lesson.mp4" type="video/mp4"><p>Your browser cannot play this video.</p></video>', ['Do not autoplay sound unexpectedly.', 'Always consider captions and a text alternative.', 'Keep fallback content useful rather than empty.'], 'Plan the accessible media assets for a tutorial video and identify a fallback for unsupported playback.'),
                    $l('Audio', 'audio', 'Embed spoken or musical audio with native controls and fallback content.', 22, 'The audio element represents sound content. Controls give users play, pause, volume, and seek features supplied by the browser.', 'Native audio is easier to access and maintain than a custom player built from scratch.', ['Use controls unless the experience provides an equivalent accessible interface.', 'Provide source types when offering alternative formats.', 'A transcript is valuable for spoken content.'], '<audio controls><source src="lesson.ogg" type="audio/ogg"><source src="lesson.mp3" type="audio/mpeg"><p>Download the audio lesson instead.</p></audio>', ['Do not hide audio controls without replacing every function.', 'Do not assume a file extension guarantees the MIME type.', 'Keep important information out of audio alone.'], 'Add an audio explanation with two source formats and a text transcript link.'),
                    $l('Video', 'video', 'Embed video with dimensions, controls, poster imagery, and alternatives.', 24, 'The video element displays moving images and can include multiple sources, a poster image, and fallback content.', 'A well-marked-up video works across more browsers and communicates its purpose before playback begins.', ['Use poster to show a representative preview.', 'Set dimensions that match the media to reduce layout shift.', 'Use track for captions and other timed text.'], '<video controls width="720" poster="mountain-preview.jpg"><source src="mountain.mp4" type="video/mp4"><track kind="captions" src="mountain-en.vtt" srclang="en" label="English"><p>Watch the text transcript instead.</p></video>', ['Captions must be synchronized and readable.', 'Do not stretch media by choosing unrelated dimensions.', 'Provide a transcript when video carries essential spoken information.'], 'Mark up a short instructional video with a poster, captions, source, and transcript fallback.'),
                    $l('Video Controls and Attributes', 'video-controls-and-attributes', 'Use media attributes to shape playback without creating unexpected behavior.', 26, 'Attributes such as muted, loop, preload, playsinline, and controls affect playback and loading. Their combination should reflect user intent and bandwidth.', 'Thoughtful defaults prevent surprise sound, conserve resources, and improve mobile playback.', ['muted is required for many autoplay scenarios.', 'preload hints how much data the browser should fetch.', 'playsinline helps mobile browsers keep playback in the page.'], '<video controls muted playsinline preload="metadata" poster="preview.jpg"><source src="demo.mp4" type="video/mp4"></video>', ['Autoplay can be disruptive and may be blocked.', 'Do not use loop for content users need to finish.', 'Preload is a hint, not a guarantee.'], 'Choose playback attributes for a silent background preview and for an on-demand tutorial, explaining the difference.'),
                    $l('Embedding External Media', 'embedding-external-media', 'Embed external pages and media responsibly with iframe.', 23, 'iframe creates a nested browsing context for another document. It can embed maps, videos, or trusted tools, but it has security and performance implications.', 'External embeds extend a page’s capabilities while requiring careful control of source, permissions, and privacy.', ['Use a specific source URL and a meaningful title.', 'sandbox can restrict what the embedded document can do.', 'loading="lazy" can defer below-the-fold embeds.'], '<iframe src="https://example.com/player" title="Workshop video player" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>', ['Do not embed untrusted content casually.', 'Avoid frame-border styling as a substitute for a useful title.', 'Check responsive dimensions and keyboard access.'], 'Evaluate an external video embed and list its source, title, loading, permissions, and privacy decisions.'),
                    $l('Canvas', 'canvas', 'Understand canvas as a script-controlled drawing surface with an accessible fallback.', 29, 'The canvas element provides a bitmap area that JavaScript can draw into. HTML supplies the surface and fallback content; scripts supply the actual drawing.', 'Canvas is useful for charts, games, and visual tools, but its pixels do not automatically expose their meaning to assistive technology.', ['Set width and height intentionally.', 'Put a useful fallback description inside canvas.', 'Expose important data in surrounding HTML or another accessible representation.'], '<canvas id="sales-chart" width="640" height="320">Sales chart: April 12, May 18, June 24.</canvas>', ['CSS size and drawing size are different concepts.', 'Do not put essential text only inside pixels.', 'Canvas rendering requires JavaScript and should degrade gracefully.'], 'Design the HTML fallback for a canvas chart before thinking about the drawing script.'),
                    $l('SVG Basics', 'svg-basics', 'Use inline SVG and accessible titles for scalable vector graphics.', 27, 'SVG is a markup language for vector graphics. Inline SVG can describe shapes and icons, while an image-like SVG should have an accessible name or alternative.', 'Vector graphics remain sharp at different sizes and can be styled or inspected as structured markup.', ['svg defines the viewport and coordinate system.', 'title and desc can describe meaningful graphics.', 'path, circle, rect, and text create visual shapes.'], '<svg viewBox="0 0 120 60" role="img" aria-labelledby="chart-title"><title id="chart-title">A rising trend line</title><path d="M5 50 L35 35 L65 38 L115 10" fill="none" stroke="currentColor"></path></svg>', ['Do not use complex graphics without an accessible name.', 'Keep decorative SVG hidden from the accessibility tree.', 'Use viewBox to support responsive scaling.'], 'Create a simple SVG icon and decide whether it is informative or decorative, then mark it up accordingly.'),
                    $l('Geolocation API', 'geolocation-api', 'Learn the HTML role in a page that requests a user’s location through the browser API.', 28, 'Geolocation is a browser capability accessed by JavaScript, not an HTML element. HTML should explain the purpose, provide a trigger, and show a meaningful status area.', 'Location data is sensitive, so the page must ask clearly, handle denial, and avoid treating permission as guaranteed.', ['Explain why location is requested before asking.', 'Provide a button or other deliberate user action.', 'Offer a useful alternative when permission is denied.'], '<p id="location-status">Your location is not requested yet.</p>\n<button type="button" id="find-nearby">Find nearby classes</button>', ['Do not request location on page load without context.', 'Never expose precise location unnecessarily.', 'Permission errors and unavailable devices are normal cases.'], 'Design the visible HTML states for location idle, requesting, success, denied, and unavailable scenarios.'),
                    $l('Web Storage', 'web-storage', 'Structure a page that explains and controls browser-local storage without confusing it with server data.', 24, 'Web Storage is accessed by JavaScript through localStorage and sessionStorage. HTML provides labels, controls, and status text for the settings or saved data experience.', 'Clear UI language helps users understand what is stored locally, for how long, and how it can be removed.', ['localStorage persists across browser sessions.', 'sessionStorage usually lasts for a tab session.', 'Storage can be unavailable or restricted.'], '<label for="theme">Theme preference</label><select id="theme" name="theme"><option value="light">Light</option><option value="dark">Dark</option></select>\n<p id="save-status" role="status">Preference is saved on this device.</p>', ['Do not store secrets in browser storage.', 'Do not imply local storage is synchronized to an account.', 'Provide a clear reset or remove action.'], 'Design a preference panel that explains local storage and offers a keyboard-accessible reset control.'),
                    $l('Building a Multimedia Web Page', 'building-a-multimedia-web-page', 'Combine media, captions, graphics, embeds, and progressive enhancement in one page.', 38, 'A multimedia page should have a clear reading structure around its media. The page must remain understandable when media is slow, blocked, or unavailable.', 'The project brings together performance, accessibility, privacy, and fallback decisions that real media pages require.', ['Use headings and text around every major media item.', 'Offer captions, transcripts, and fallback descriptions.', 'Lazy-load nonessential embeds and keep sensitive APIs opt-in.'], '<main><h1>Field notes</h1><figure><video controls poster="field.jpg"><source src="field.mp4" type="video/mp4"><track kind="captions" src="field.vtt" srclang="en" label="English"></video><figcaption>Observations from the field.</figcaption></figure><p><a href="/transcript">Read the transcript</a></p></main>', ['Do not make a media page depend on one browser or network condition.', 'Review focus order and keyboard controls.', 'Keep the main lesson available in text.'], 'Plan a multimedia article with one video, one audio clip, an SVG map, and an external embed, including fallbacks.'),
                ],
            ],
            [
                'title' => 'Advanced HTML Structure',
                'slug' => 'advanced-html-structure',
                'description' => 'Take your HTML skills deeper by learning advanced document structure, meta tags, SEO-friendly markup, iframes, and organizing large web pages properly.',
                'level' => 3,
                'estimated_duration' => 5,
                'lessons' => [
                    $l('Advanced Document Structure', 'advanced-document-structure', 'Organize complex pages with deliberate regions, nesting, and document order.', 28, 'Advanced structure is about making relationships explicit as a page grows. Landmarks, headings, sections, articles, and supporting content should reflect the user’s mental model.', 'A clear structure keeps large documents maintainable and lets styles, scripts, search tools, and assistive technology work with the same content model.', ['Use landmarks for major regions.', 'Keep source order aligned with reading and interaction order.', 'Nest sections only when their hierarchy is meaningful.'], '<body><header>...</header><main><article><header>...</header><section>...</section><footer>...</footer></article><aside>...</aside></main><footer>...</footer></body>', ['Do not use source order only to satisfy a visual layout.', 'Avoid excessive landmark repetition.', 'Give repeated components consistent internal structure.'], 'Map the regions of a news homepage and explain which content belongs in main, article, aside, and footer.'),
                    $l('Meta Tags', 'meta-tags', 'Use head metadata to describe encoding, viewport behavior, and document information.', 24, 'Meta elements provide information about a document that is not normally shown in the page body. Common metadata includes character encoding, viewport settings, descriptions, and robots instructions.', 'Good metadata improves rendering, sharing, search presentation, and compatibility across devices.', ['charset should be declared early.', 'The viewport meta tag supports responsive layout behavior.', 'Descriptions should summarize the page honestly.'], '<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Guided HTML lessons for new developers"><title>HTML Lessons</title></head>', ['Do not use meta keywords as a modern search strategy.', 'Do not duplicate the title and description across every page.', 'Metadata does not replace visible content.'], 'Write a head section for a lesson page with title, description, viewport, and a canonical URL placeholder.'),
                    $l('SEO-Friendly HTML', 'seo-friendly-html', 'Structure content so search engines and people can understand its topic and hierarchy.', 27, 'Search-friendly HTML begins with useful content, a descriptive title, logical headings, meaningful links, and structured page information.', 'Search engines need to understand relevance, but the same clarity also helps people scan and share the page.', ['Use one clear page topic and descriptive title.', 'Write headings and links that describe content.', 'Use semantic elements and appropriate structured data when justified.'], '<article><h1>Beginner HTML Forms Guide</h1><p>Learn how labels, input types, and validation create reliable forms.</p><h2>Choose controls</h2><a href="/html-forms/examples">View form examples</a></article>', ['Do not stuff keywords unnaturally.', 'Do not hide important content only for crawlers.', 'Avoid duplicate pages with unclear canonical ownership.'], 'Improve the structure of a poorly labeled article and list the changes that help both readers and search tools.'),
                    $l('Open Graph Metadata', 'open-graph-metadata', 'Prepare pages for rich previews when shared on social platforms.', 20, 'Open Graph metadata uses properties such as title, description, type, URL, and image to describe a shared page.', 'A clear preview helps people decide whether a shared link is relevant before opening it.', ['Use og:title and og:description for the preview copy.', 'Use og:url for the preferred page URL.', 'Use an appropriately sized, meaningful og:image.'], '<meta property="og:title" content="HTML Forms Guide">\n<meta property="og:description" content="Build clear, validated HTML forms.">\n<meta property="og:type" content="article">\n<meta property="og:url" content="https://example.com/forms">', ['Keep preview text accurate and consistent with the page.', 'Do not use an unrelated image for attention.', 'Test previews because platforms may cache metadata.'], 'Write Open Graph metadata for a course landing page and choose an image that represents its content.'),
                    $l('Favicon and Web App Metadata', 'favicon-and-web-app-metadata', 'Add icons and metadata that identify a site in browser and installed contexts.', 21, 'Favicons and web app metadata help users recognize a site in tabs, bookmarks, home screens, and install prompts.', 'Consistent identity reduces confusion when people have many pages or applications open.', ['Use link rel="icon" for a favicon.', 'Use a web app manifest for installable metadata.', 'Choose icons that remain recognizable at small sizes.'], '<link rel="icon" href="/favicon.svg" type="image/svg+xml">\n<link rel="manifest" href="/site.webmanifest">\n<meta name="theme-color" content="#0f172a">', ['Do not assume one icon size works everywhere.', 'Manifest metadata does not make an application offline by itself.', 'Keep brand contrast and accessibility in mind.'], 'Create the head links for a small site and list the icon and manifest assets it would need.'),
                    $l('Iframes', 'iframes', 'Use iframes with clear titles, sizing, and security restrictions.', 25, 'An iframe embeds another document inside the current document. It creates a boundary, but it does not automatically make external content trustworthy or responsive.', 'Careful iframe use protects users and keeps embedded content understandable.', ['title describes the embedded document.', 'sandbox limits capabilities unless permissions are added.', 'loading and dimensions affect performance and layout.'], '<iframe src="/calendar.html" title="Community events calendar" sandbox="allow-scripts" loading="lazy" width="800" height="500"></iframe>', ['Do not allow unnecessary sandbox permissions.', 'Do not embed pages that refuse framing without a fallback.', 'Explain embedded content and its origin when trust matters.'], 'Review an iframe embed and propose a title, sandbox policy, fallback link, and responsive sizing strategy.'),
                    $l('Embedded External Content', 'embedded-external-content', 'Make deliberate choices when including third-party content, widgets, or documents.', 24, 'External content can add maps, payment widgets, documents, or video, but it can also add tracking, network cost, and a dependency outside your control.', 'Thinking through trust, privacy, failure, and fallback makes integrations safer and more resilient.', ['Load third-party content only when it serves a clear user need.', 'Explain external origins and permissions.', 'Offer a direct link or text alternative when the embed fails.'], '<section aria-labelledby="map-heading"><h2 id="map-heading">Find us</h2><iframe src="https://maps.example.test/embed" title="Map showing the learning center" loading="lazy"></iframe><p><a href="/directions">Open written directions</a></p></section>', ['Do not hide essential instructions inside a third-party frame.', 'Review provider terms and privacy behavior.', 'Use lazy loading for below-the-fold content where appropriate.'], 'Create a fallback plan for a map, document viewer, and payment widget before embedding any of them.'),
                    $l('HTML Templates and Data Attributes', 'html-templates-and-data-attributes', 'Understand inert templates and custom data attributes for progressive interfaces.', 28, 'The template element stores markup that is not rendered until a script chooses to clone it. data-* attributes store small custom values associated with an element.', 'These tools let a page keep structured HTML close to the content while JavaScript progressively enhances it.', ['template content is inert until used by a script.', 'data-* names should describe stable application data.', 'Do not place secrets in data attributes because they are visible to users.'], '<template id="course-card"><article class="card" data-course-slug="html"><h2></h2><p></p></article></template>\n<button type="button" data-action="load-course">Load course</button>', ['Data attributes are not a replacement for semantic attributes.', 'Keep data values small and safe to expose.', 'Provide a useful non-script experience where possible.'], 'Design a course-card template with data attributes for a public slug and display label.'),
                    $l('Organizing Large HTML Documents', 'organizing-large-html-documents', 'Apply naming, ordering, and sectioning rules to pages with substantial content.', 30, 'Large documents need a predictable rhythm: a clear head, landmarks, headings, reusable patterns, and source order that matches the user journey.', 'Consistent organization reduces accidental nesting errors and makes future content changes safer.', ['Keep one responsibility per section.', 'Use repeated patterns consistently across related content.', 'Place supporting content near the thing it supports.'], '<main><h1>Product handbook</h1><nav aria-label="On this page"><a href="#setup">Setup</a><a href="#workflow">Workflow</a></nav><section id="setup"><h2>Setup</h2>...</section><section id="workflow"><h2>Workflow</h2>...</section></main>', ['Do not create a table of contents that points to unstable ids.', 'Avoid very deep heading hierarchies.', 'Use comments sparingly; good structure should explain itself.'], 'Create an outline for a long handbook with a table of contents and three logically nested sections.'),
                    $l('Advanced Page Structure Project', 'advanced-page-structure-project', 'Design a production-minded HTML structure using metadata, landmarks, articles, embeds, and progressive enhancement.', 38, 'The final project combines document head information, semantic regions, content hierarchy, external content boundaries, and data prepared for enhancement.', 'A complete structure is the best test of whether individual HTML decisions still work together on a realistic page.', ['Start from user tasks and content relationships.', 'Include metadata and a meaningful page outline.', 'Document fallbacks and trust boundaries for embedded content.'], '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="description" content="A structured project guide"><title>Project Guide</title></head><body><header>...</header><main><article><h1>Project guide</h1><section>...</section></article><aside>...</aside></main><footer>...</footer></body></html>', ['Do not add advanced tags without a clear purpose.', 'Validate the outline and links before styling.', 'Keep essential content available without optional enhancements.'], 'Plan and document the structure of a multi-section project guide, including its head metadata and fallback strategy.'),
                ],
            ],
            [
                'title' => 'Building Real Web Pages with HTML',
                'slug' => 'building-real-web-pages-html',
                'description' => 'Apply everything you’ve learned by building complete, real-world web pages. This practical course focuses on structuring full websites using only HTML.',
                'level' => 3,
                'estimated_duration' => 7,
                'lessons' => [
                    $l('Planning a Web Page', 'planning-a-web-page', 'Turn a page goal and audience into a content outline before writing markup.', 28, 'Planning starts with the user’s task, the information they need, and the action the page should support. An outline prevents markup from becoming a random collection of elements.', 'Good planning reduces rework and produces pages that are easier to navigate, style, and test.', ['Identify audience, purpose, content, and primary action.', 'Create a heading outline before detailed markup.', 'List required media, links, forms, and states.'], '<h1>Neighborhood workshop</h1>\n<h2>What you will learn</h2>\n<h2>Schedule</h2>\n<h2>Register</h2>', ['Do not start with colors or layout before understanding content.', 'Do not make every piece of information an equal priority.', 'Keep the primary task visible in the outline.'], 'Create a content brief and heading outline for a local event page.'),
                    $l('Building a Website Header', 'building-a-website-header', 'Create a recognizable, useful site header with branding and primary context.', 24, 'A website header introduces the site or page. It often contains a brand link, site title, and primary navigation, but it should remain focused.', 'A predictable header helps users understand where they are and move to the most important areas.', ['Use a heading or clear brand name.', 'Link the brand to a sensible home destination.', 'Keep primary navigation grouped and labeled.'], '<header><a href="/" aria-label="Acme Learning home"><strong>Acme Learning</strong></a><p>Practical web lessons</p></header>', ['Do not make branding the only way to reach home without a clear link.', 'Do not put every utility action in the primary header.', 'Keep header reading order logical on mobile.'], 'Mark up a site header for a learning center with a brand link, tagline, and primary navigation.'),
                    $l('Creating Navigation', 'creating-navigation', 'Build navigation that helps users move through a single page and a multi-page site.', 25, 'Navigation is a set of meaningful links grouped in a nav landmark. It can represent primary pages, local sections, or the current page context.', 'Clear navigation reduces orientation problems and supports keyboard and assistive-technology users.', ['Use descriptive link text and a label for each nav purpose.', 'Use fragment links for sections on the same page.', 'Indicate the current page with aria-current when appropriate.'], '<nav aria-label="Primary"><a href="/" aria-current="page">Home</a><a href="/services">Services</a><a href="/contact">Contact</a></nav>', ['Do not use buttons for ordinary navigation.', 'Do not rely only on visual highlighting for the current page.', 'Avoid duplicate menus with unclear labels.'], 'Create primary and in-page navigation for a long services page and identify the current location.'),
                    $l('Building a Hero Section', 'building-a-hero-section', 'Structure a prominent introduction without losing semantic clarity or useful content.', 24, 'A hero is a prominent introductory region, not a special HTML element. Its structure usually includes a heading, supporting text, and one or more actions.', 'A focused introduction tells users what the page offers and gives them a clear next step.', ['Use a meaningful heading as the page topic.', 'Write supporting text that explains value or context.', 'Use a link for navigation and a button for an in-page action.'], '<section aria-labelledby="hero-title"><h1 id="hero-title">Learn by building</h1><p>Short lessons help you understand the structure behind real web pages.</p><p><a href="#courses">Browse courses</a></p></section>', ['Do not put the only essential information in a background image.', 'Do not create multiple competing h1 elements without a reason.', 'Keep calls to action understandable out of context.'], 'Write the HTML-only hero for a course site with a clear promise and two purposeful links.'),
                    $l('Creating About Sections', 'creating-about-sections', 'Explain people, organizations, or products with well-organized about content.', 23, 'About sections answer who, what, why, and how. They work best when information is grouped by topic rather than presented as one undifferentiated paragraph.', 'A clear about section builds trust and lets readers quickly find the details relevant to them.', ['Use sections with descriptive headings.', 'Use figure for portraits or diagrams with captions.', 'Use lists for values, history, or team responsibilities when appropriate.'], '<section aria-labelledby="about-title"><h2 id="about-title">About the studio</h2><p>We help local teams publish clear information.</p><h3>Our values</h3><ul><li>Clarity</li><li>Care</li><li>Learning</li></ul></section>', ['Do not make claims without useful supporting information.', 'Keep biographies and organization descriptions scannable.', 'Use alt text that matches the purpose of an about image.'], 'Build an about section for a small organization with mission, values, and one team profile.'),
                    $l('Services and Features Sections', 'services-and-features-sections', 'Present offerings and product capabilities in a structure readers can compare.', 26, 'Services and features should explain what is offered, who it helps, and what distinguishes each item. Repeated items often work well as articles inside a section.', 'Consistent structure helps readers compare options and makes future content easier to maintain.', ['Use a section heading for the collection.', 'Use article for a self-contained service or feature.', 'Use headings and concise supporting text for each item.'], '<section aria-labelledby="services-title"><h2 id="services-title">What we offer</h2><article><h3>Workshops</h3><p>Practice with an instructor.</p></article><article><h3>Reviews</h3><p>Receive focused feedback.</p></article></section>', ['Do not present marketing claims without explaining the service.', 'Keep repeated cards structurally consistent.', 'Do not use a list or article solely because it has a border in the design.'], 'Mark up three services with a shared structure and explain which information belongs in every item.'),
                    $l('Creating Contact Sections', 'creating-contact-sections', 'Give users clear ways to contact an organization through address details, links, and forms.', 27, 'A contact section can include an address, email link, telephone link, hours, and a form. Each option should have a clear purpose and accessible label.', 'Multiple contact methods support different needs and reduce uncertainty about what happens after a submission.', ['Use address for physical contact information.', 'Use mailto and tel links carefully and label their purpose.', 'Connect form controls to visible labels and instructions.'], '<section aria-labelledby="contact-title"><h2 id="contact-title">Contact us</h2><address>24 Market Street<br>Riverside</address><p><a href="mailto:hello@example.com">Email the team</a></p><p><a href="tel:+15550123">Call 555-0123</a></p></section>', ['Do not publish private contact information accidentally.', 'Explain response times for forms.', 'Use a real subject and recipient strategy behind mail links.'], 'Create a contact section with an address, hours, email, phone, and a short accessible inquiry form.'),
                    $l('Creating a Footer', 'creating-a-footer', 'Close a page with useful secondary navigation, ownership, and supporting information.', 20, 'A footer can contain related links, contact information, copyright, language choices, or policies. It should help users complete secondary tasks without competing with the main content.', 'A consistent footer gives a site a reliable ending and a place for information users expect to find.', ['Use a footer landmark for page or section closing content.', 'Group links by purpose and label groups when necessary.', 'Keep legal and accessibility links discoverable.'], '<footer><nav aria-label="Footer navigation"><a href="/privacy">Privacy</a><a href="/accessibility">Accessibility</a><a href="/contact">Contact</a></nav><p>© 2026 Acme Learning</p></footer>', ['Do not put the entire site navigation in an unlabeled footer list.', 'Keep copyright text accurate.', 'Make footer links keyboard reachable like every other link.'], 'Build a footer with policy links, contact information, social links, and a short ownership statement.'),
                    $l('Building a Multi-Page Website', 'building-a-multi-page-website', 'Connect several HTML documents into a consistent, navigable site.', 34, 'A multi-page site divides content into focused documents while keeping shared navigation and identity consistent. Each page still needs its own title and main heading.', 'Splitting content improves focus, sharing, and maintenance when one page would become too long.', ['Use stable relative links between pages.', 'Give each page a unique title and h1.', 'Keep shared header and footer structures consistent.'], '<nav aria-label="Primary"><a href="index.html">Home</a><a href="about.html">About</a><a href="services.html">Services</a><a href="contact.html">Contact</a></nav>', ['Do not leave links pointing to development-only paths.', 'Do not duplicate large unrelated content on every page.', 'Test navigation from every page, including the footer.'], 'Plan four connected pages for a small business and list each page’s title, h1, purpose, and incoming links.'),
                    $l('Final HTML Website Project', 'final-html-website-project', 'Bring the full course together by planning and marking up a complete HTML website.', 42, 'The final project is a content-first website with a shared structure, several pages, meaningful navigation, accessible media or forms, and clear metadata.', 'Completing a realistic project proves that HTML is more than isolated tags: it is a system for communicating structure and intent.', ['Plan the site map and shared regions first.', 'Build each page around one main task and heading hierarchy.', 'Review semantics, accessibility, links, metadata, and fallbacks.'], '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Acme Learning</title></head><body><header>...</header><main><h1>Learn by building</h1><section>...</section></main><footer>...</footer></body></html>', ['Do not add pages without a distinct purpose.', 'Do not treat visual polish as a substitute for readable structure.', 'Test the final site with keyboard navigation and without optional media.'], 'Design and implement the HTML structure for a four-page website, then submit a checklist covering every major course topic.'),
                ],
            ],
        ];
    }
}
