<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;

class HtmlLessonsSeeder extends Seeder
{
    public function run(): void
    {
        $records = [];
        $now = now();

        foreach ($this->courses() as $courseId => $lessons) {
            foreach ($lessons as $index => $lesson) {
                $records[] = [
                    'course_id' => $courseId,
                    'title' => $lesson['title'],
                    'slug' => $lesson['slug'],
                    'description' => $lesson['description'],
                    'content' => $this->content($lesson),
                    'lesson_order' => $index + 1,
                    'estimated_minutes' => $lesson['minutes'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
        }

        if (count($records) !== 48) {
            throw new InvalidArgumentException('HtmlLessonsSeeder must provide exactly 48 lessons.');
        }

        DB::table('lessons')->insert($records);
    }

    private function content(array $lesson): string
    {
        $objectives = $this->listItems($lesson['objectives']);
        $bestPractices = $this->listItems($lesson['best_practices']);
        $pitfalls = $this->listItems($lesson['pitfalls']);
        $code = htmlspecialchars($lesson['example'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');

        return '<h3>Requirements &amp; Tools</h3>'
            . '<p>Use Visual Studio Code and a modern web browser such as Chrome, Firefox, or Edge. Create a basic text-editing workspace, save the lesson exercise as an HTML file, and open it in the browser while keeping the source editor available.</p>'
            . '<p>Work in a clearly named project folder. Make a small edit, save, reload the browser, and compare the rendered result with the markup so that each change has an observable outcome.</p>'
            . '<h3>Lesson Objectives</h3><ul class="list-disc pl-5">' . $objectives . '</ul>'
            . '<h3>Main Lesson Content</h3>'
            . '<p>' . $this->escape($lesson['explanation']) . '</p>'
            . '<p>In a real page, begin with the user task and the information the page must communicate. Choose native HTML elements that express those relationships, keep the source order understandable, and verify the page in the browser as well as in the editor. HTML describes document structure and meaning; presentation and behavior should be added only when the content model is clear.</p>'
            . '<h4>Practical Example</h4><pre><code>' . $code . '</code></pre>'
            . '<h4>Best Practices</h4><ul class="list-disc pl-5">' . $bestPractices . '</ul>'
            . '<h4>Common Pitfalls to Avoid</h4><ul class="list-disc pl-5">' . $pitfalls . '</ul>'
            . '<h4>Practice</h4><p>' . $this->escape($lesson['practice']) . '</p>';
    }

    private function listItems(array $items): string
    {
        return implode('', array_map(
            fn (string $item): string => '<li>' . $this->escape($item) . '</li>',
            $items
        ));
    }

    private function escape(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }

    private function courses(): array
    {
        return [
            1 => [
                $this->lesson('HTML and the Web', 'html-fundamentals-html-and-the-web', 'Understand HTML as the structural language browsers parse into a document tree.', 18,
                    ['Explain the roles of HTML, CSS, and JavaScript.', 'Describe how a browser parses elements into the DOM.', 'Create and inspect a first HTML page.'],
                    'HTML is a markup language: elements label content as headings, paragraphs, links, images, and other structures. A browser parses those declarations into a Document Object Model (DOM), which other browser features can inspect. HTML does not describe an algorithm; it describes the content and relationships that make a document understandable.',
                    '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>First page</title>\n  </head>\n  <body>\n    <h1>Welcome</h1>\n    <p>This page has meaningful structure.</p>\n  </body>\n</html>',
                    ['Use HTML for meaning and structure, CSS for presentation, and JavaScript for behavior.', 'Keep one clear page topic and a readable source order.'],
                    ['Do not select elements only for their default visual size.', 'Do not assume that a page rendering without errors means its markup is well structured.'],
                    'Create a short profile page and label its title, heading, biography, and one useful destination with appropriate HTML elements.'),
                $this->lesson('Document Skeleton and Metadata', 'html-fundamentals-document-skeleton', 'Build a complete document with doctype, language, head metadata, and visible body content.', 22,
                    ['Write the standard HTML document skeleton.', 'Set the document language and character encoding.', 'Distinguish metadata in head from page content in body.'],
                    'A reliable document begins with the HTML doctype and one html root element. The lang attribute helps pronunciation and language tools; charset declares text encoding; title names the browser tab and document; viewport metadata gives mobile browsers a useful layout width. Visible page content belongs in body, while descriptive metadata belongs in head.',
                    '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <title>Neighborhood Garden</title>\n  </head>\n  <body>\n    <main><h1>Neighborhood Garden</h1></main>\n  </body>\n</html>',
                    ['Declare the correct human language on the html element.', 'Give every page a concise, distinct title.'],
                    ['Do not put visible headings in head.', 'Do not omit the doctype or place unrelated content outside the root html element.'],
                    'Make a complete document for a local event, including language, encoding, viewport metadata, a unique title, and one main heading.'),
                $this->lesson('Elements, Tags, and Attributes', 'html-fundamentals-elements-tags-attributes', 'Read element syntax and use attributes to add an element value or relationship.', 20,
                    ['Identify start tags, end tags, and element content.', 'Use attributes in an opening tag.', 'Recognize void elements that have no closing tag.'],
                    'An element is represented by tags and the content between them. Attributes add information such as an identifier, destination, or alternative text. Attribute values should be quoted consistently. Some elements, including img and meta, are void elements and do not wrap content or use an end tag.',
                    '<p class="intro">Read the <a href="guide.html">HTML guide</a>.</p>\n<img src="diagram.png" alt="A document tree with nested elements">',
                    ['Use lowercase element and attribute names for consistent source.', 'Quote attribute values and choose descriptive identifiers.'],
                    ['Do not omit required closing tags for non-void elements.', 'Do not add a slash to imply that a void element can contain content.'],
                    'Annotate a short HTML fragment by identifying each element, its attributes, and which elements contain other elements.'),
                $this->lesson('Headings and Content Hierarchy', 'html-fundamentals-headings-hierarchy', 'Organize a page with a logical heading outline and well-scoped sections.', 22,
                    ['Use h1 through h6 to express nested heading levels.', 'Create a page outline that reflects the topic hierarchy.', 'Use headings to help readers scan long content.'],
                    'Heading elements identify the topic of the page or a subsection. Their numeric level communicates nesting, not a preferred font size. A page should begin with a clear top-level heading and use lower levels for sections and subsections, with no skipped level unless the structure genuinely calls for it.',
                    '<main>\n  <h1>Planning a Community Event</h1>\n  <section>\n    <h2>Choose a date</h2>\n    <p>Check the venue calendar before announcing the event.</p>\n    <h3>Confirm availability</h3>\n    <p>Ask the venue to hold the date.</p>\n  </section>\n</main>',
                    ['Write headings that describe the section content.', 'Review the outline without relying on visual styling.'],
                    ['Do not choose h4 because its default font looks right.', 'Do not use headings as empty spacing elements.'],
                    'Outline an article about preparing a garden with one h1, several h2 sections, and a correctly nested subsection.'),
                $this->lesson('Paragraphs and Text Semantics', 'html-fundamentals-paragraphs-text', 'Use paragraphs and inline semantic elements to express emphasis, importance, and quotations.', 20,
                    ['Group prose into paragraphs.', 'Distinguish importance from emphasis.', 'Mark quotations and edits with suitable elements.'],
                    'The p element groups a coherent block of prose. Strong communicates importance; em marks stress emphasis; blockquote groups a longer quotation; q can represent a short inline quotation. These elements describe how text functions, allowing browser styles and assistive tools to convey meaning beyond appearance.',
                    '<article>\n  <h1>Field Notes</h1>\n  <p><strong>Safety:</strong> Wear gloves when handling compost.</p>\n  <p><em>Remember</em> to water new seedlings gently.</p>\n  <blockquote><p>Healthy soil supports a resilient garden.</p></blockquote>\n</article>',
                    ['Choose semantic text elements based on meaning.', 'Keep paragraphs focused on one connected idea.'],
                    ['Do not use repeated br elements to create paragraph spacing.', 'Do not use b or i as a replacement when strong or em meaning is intended.'],
                    'Edit a short announcement into focused paragraphs and mark one important warning and one emphasized instruction.'),
                $this->lesson('Links and URL Paths', 'html-fundamentals-links-url-paths', 'Create descriptive links and choose appropriate relative or absolute destinations.', 24,
                    ['Create links with the anchor element and href.', 'Distinguish relative paths from absolute URLs.', 'Write link text that names the destination or action.'],
                    'An anchor with href navigates to a resource. Relative paths resolve from the current document location; absolute URLs include the full scheme and host. Fragment identifiers can jump to an element with a matching id. Link text should make sense when read independently from surrounding paragraphs.',
                    '<nav aria-label="Course pages">\n  <a href="index.html">Course home</a>\n  <a href="lessons/forms.html">Form lessons</a>\n</nav>\n<p><a href="https://developer.mozilla.org/">Read the MDN HTML reference</a></p>',
                    ['Use a link for navigation and a button for an action.', 'Check every destination and use descriptive link text.'],
                    ['Avoid vague text such as click here.', 'Do not use a button element merely to navigate to another URL.'],
                    'Build a three-link course navigation using a mix of relative internal paths and one clearly named external reference.'),
                $this->lesson('Images and Alternative Text', 'html-fundamentals-images-alt-text', 'Embed images with correct source paths, useful alternatives, and optional captions.', 24,
                    ['Add images with img and src.', 'Write alternative text based on image purpose.', 'Group a figure with a caption when context is needed.'],
                    'The img element embeds an image resource. Its alt text is the textual replacement available when the image cannot be perceived. Informative images need a concise description of their relevant information; decorative images should generally use an empty alt value. Figure and figcaption associate an image with a visible caption.',
                    '<figure>\n  <img src="seedlings.jpg" alt="Three tomato seedlings growing beside a sunny window" width="640" height="420">\n  <figcaption>Seedlings started indoors in early spring.</figcaption>\n</figure>',
                    ['Write alt text for the image purpose in its page context.', 'Set intrinsic width and height to reduce layout movement.'],
                    ['Do not use a filename as the alternative.', 'Do not repeat the full caption in alt when it adds no extra information.'],
                    'Add one informative and one decorative image to an article and decide what the alt value for each should be.'),
                $this->lesson('Lists and Data Tables', 'html-fundamentals-lists-tables', 'Represent ordered steps, unordered collections, and genuinely tabular data accurately.', 26,
                    ['Choose ul or ol based on whether sequence matters.', 'Use li for each list item.', 'Structure tabular data with captions and header cells.'],
                    'Lists expose a group and its item count in a way that is useful for scanning and assistive technology. Use ol when order or ranking matters and ul otherwise. Tables are for data relationships, not layout; caption identifies the dataset, while th and scope associate labels with columns or rows.',
                    '<h2>Publishing checklist</h2>\n<ol><li>Draft the content.</li><li>Check links.</li><li>Review the page.</li></ol>\n<table><caption>Workshop seats</caption><thead><tr><th scope="col">Session</th><th scope="col">Seats</th></tr></thead><tbody><tr><th scope="row">Morning</th><td>12</td></tr></tbody></table>',
                    ['Use list elements for real collections.', 'Give tables clear captions and row or column headings.'],
                    ['Do not use a table to position page sections.', 'Do not put text directly under ul or ol without an li wrapper.'],
                    'Create an ordered set of setup steps and a small attendance table with a caption plus row and column headers.'),
            ],
            9 => [
                $this->lesson('Form Structure and Submission', 'html-forms-structure-submission', 'Build a form boundary and understand how named controls become submitted data.', 22,
                    ['Use form to group one submission workflow.', 'Set action and method for the intended endpoint.', 'Add name values to data-bearing controls.'],
                    'A form gathers controls and submits successful named values to its action. GET is useful for non-sensitive searches whose state can be bookmarked; POST is commonly used to create or change data. The server must parse and validate the received values independently of browser-side rules.',
                    '<form action="/registrations" method="post">\n  <label for="event-name">Event</label>\n  <input id="event-name" name="event_name" required>\n  <button type="submit">Register</button>\n</form>',
                    ['Choose a method based on the action and data sensitivity.', 'Give every submitted control a stable name.'],
                    ['Do not put passwords or private data in GET query strings.', 'Do not rely on client-side validation as a security boundary.'],
                    'Design a search form and a registration form, explaining which method each should use and what values it submits.'),
                $this->lesson('Labels, Instructions, and Grouping', 'html-forms-labels-instructions-grouping', 'Connect visible labels and help text to controls and group related choices.', 24,
                    ['Associate labels using matching for and id values.', 'Use fieldset and legend for related controls.', 'Provide instructions before users need them.'],
                    'A label gives a control a programmatic name and a larger click target. Explicit labels connect for to the input id. Fieldset and legend name a set of related options, such as a radio group. Help text should be close to its control and can be connected with aria-describedby when needed.',
                    '<form>\n  <fieldset>\n    <legend>Preferred contact</legend>\n    <label><input type="radio" name="contact" value="email"> Email</label>\n    <label><input type="radio" name="contact" value="phone"> Phone</label>\n  </fieldset>\n  <label for="details">Additional details</label>\n  <textarea id="details" name="details" aria-describedby="details-help"></textarea>\n  <p id="details-help">Do not include confidential information.</p>\n</form>',
                    ['Keep labels visible and specific.', 'Use fieldset only when controls form a meaningful group.'],
                    ['Placeholder text is not a sufficient label.', 'Do not use the same id for multiple controls.'],
                    'Mark up a contact preference group and a comments field with labels, a legend, and useful help text.'),
                $this->lesson('Text, Email, URL, and Password Controls', 'html-forms-text-email-url-password', 'Choose single-line input types that match the value and enable useful browser assistance.', 22,
                    ['Select text, email, url, or password input types.', 'Use autocomplete values for common personal data.', 'Explain length or format constraints.'],
                    'Input type communicates the expected value and can change mobile keyboard layout and built-in validity checks. Email and URL types catch some malformed values but do not prove that an address exists. Password masks visual characters, but security depends on transport and server handling. Autocomplete hints help browsers fill known fields.',
                    '<label for="name">Full name</label><input id="name" name="name" autocomplete="name" required>\n<label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required>\n<label for="website">Website</label><input id="website" name="website" type="url">\n<label for="new-password">New password</label><input id="new-password" name="password" type="password" autocomplete="new-password" minlength="12">',
                    ['Use autocomplete tokens that describe the requested data.', 'Use input types to improve both validation and device entry.'],
                    ['Do not assume type=email checks ownership or deliverability.', 'Do not send passwords over insecure transport or expose them in URLs.'],
                    'Build a profile form with name, email, website, and password controls and document the browser assistance each type provides.'),
                $this->lesson('Number, Date, and Range Controls', 'html-forms-number-date-range', 'Collect quantities, dates, and approximate bounded values with appropriate controls.', 24,
                    ['Use number for numeric quantities.', 'Set min, max, and step constraints deliberately.', 'Pair range with a readable current value.'],
                    'Number represents a quantity suitable for numeric operations. Date represents a calendar date without a time zone. Range is a slider for selecting within bounds when an approximate visual choice is appropriate. Constraints improve browser feedback but server-side code must repeat important rules.',
                    '<label for="guests">Number of guests</label><input id="guests" name="guests" type="number" min="1" max="12" step="1" required>\n<label for="arrival">Arrival date</label><input id="arrival" name="arrival" type="date" required>\n<label for="brightness">Brightness: <output id="brightness-value">60</output>%</label><input id="brightness" name="brightness" type="range" min="0" max="100" value="60">',
                    ['Use a range only when a slider suits the user task.', 'Display units and the current range value in understandable text.'],
                    ['Do not use number for phone numbers or postal codes.', 'Do not assume every browser presents date controls identically.'],
                    'Select controls for a booking form with guest count, arrival date, and a non-critical preference slider.'),
                $this->lesson('Select, Checkbox, and Radio Controls', 'html-forms-select-checkbox-radio', 'Represent one choice, multiple independent choices, and long fixed option sets.', 25,
                    ['Group mutually exclusive radio inputs by name.', 'Use checkboxes for independent selections.', 'Use select when a compact fixed choice list is appropriate.'],
                    'Radio controls with the same name form a one-of-many choice. Checkboxes are independent and can submit multiple values when names use an array convention supported by the server. Select with option is effective for a fixed list, but very long lists can be difficult to scan and should be reconsidered.',
                    '<fieldset><legend>Plan</legend><label><input type="radio" name="plan" value="basic" required> Basic</label><label><input type="radio" name="plan" value="plus"> Plus</label></fieldset>\n<fieldset><legend>Topics</legend><label><input type="checkbox" name="topics[]" value="forms"> Forms</label><label><input type="checkbox" name="topics[]" value="media"> Media</label></fieldset>\n<label for="region">Region</label><select id="region" name="region"><option value="">Choose a region</option><option value="north">North</option></select>',
                    ['Make every option label explicit and useful.', 'Provide an empty prompt option where a selection is required.'],
                    ['Do not use separate names for mutually exclusive radios.', 'Do not preselect consent choices when an explicit decision is required.'],
                    'Create a course enrollment form with one plan choice, two optional topic interests, and a required region.'),
                $this->lesson('Textarea, File, and Hidden Values', 'html-forms-textarea-file-hidden', 'Handle longer input and file selection while understanding hidden field limitations.', 24,
                    ['Use textarea for multi-line text.', 'Configure file controls and accepted formats as hints.', 'Treat hidden input values as untrusted client data.'],
                    'Textarea accepts longer text and supports a helpful starting size with rows and cols. File input exposes a file chooser; accept can guide selection but does not validate the file safely. Hidden controls submit values without displaying them, yet users can inspect or change them, so they must never be trusted for authorization or pricing.',
                    '<label for="message">Project summary</label><textarea id="message" name="message" rows="6" maxlength="1200" required></textarea>\n<label for="attachment">Attach a brief</label><input id="attachment" name="attachment" type="file" accept=".pdf,.docx">\n<input type="hidden" name="form_version" value="2026-10">',
                    ['Explain upload size and permitted file types near the control.', 'Validate uploaded content and hidden values on the server.'],
                    ['Do not treat accept as a security validation.', 'Do not place secrets or trusted business decisions in hidden fields.'],
                    'Add a project summary, optional document upload, and harmless form version value, then list server checks required for each.'),
                $this->lesson('Native Constraint Validation', 'html-forms-native-constraint-validation', 'Apply required, length, pattern, and range constraints with helpful user guidance.', 27,
                    ['Apply required and type-specific constraints.', 'Use minlength, maxlength, min, max, and step.', 'Write understandable format instructions for pattern.'],
                    'Constraint validation lets the browser identify common input errors before form submission. Required checks presence; length and numeric constraints bound values; pattern matches a required text format. A pattern is a regular expression for the whole value, and its user-facing instructions should explain the expected format clearly.',
                    '<label for="invite">Invite code</label><input id="invite" name="invite" pattern="[A-Z]{3}-[0-9]{4}" title="Use three capital letters, a dash, and four digits" required>\n<label for="seats">Seats</label><input id="seats" name="seats" type="number" min="1" max="8" required>\n<button type="submit">Continue</button>',
                    ['Choose constraints that match real product rules.', 'Provide visible instructions before a validation error occurs.'],
                    ['Do not assume the browser prevents crafted HTTP requests.', 'Avoid opaque patterns that users cannot correct from the error alone.'],
                    'Add validation to an event registration form and write the instruction users need before each field is submitted.'),
                $this->lesson('Accessible Error Feedback and Form Project', 'html-forms-accessible-errors-project', 'Design a complete form with clear error states and an accessible correction path.', 30,
                    ['Plan labels, help text, and validation before writing controls.', 'Associate error text with the relevant field.', 'Review keyboard order and submitted field names.'],
                    'A useful form does more than reject invalid values: it explains what is wrong, identifies the field, and tells the user how to recover. Connect error and help text with aria-describedby, expose required status in text, preserve entered values after correction, and repeat all validation on the server.',
                    '<form action="/workshops" method="post">\n  <h2>Workshop registration</h2>\n  <label for="attendee">Name</label><input id="attendee" name="name" autocomplete="name" required aria-describedby="attendee-error">\n  <p id="attendee-error" role="status">Enter your full name.</p>\n  <label for="attendee-email">Email address</label><input id="attendee-email" name="email" type="email" autocomplete="email" required>\n  <button type="submit">Register</button>\n</form>',
                    ['Keep error language specific, polite, and actionable.', 'Ensure keyboard focus and reading order reach every field and message.'],
                    ['Do not communicate errors only with red color.', 'Do not erase valid form entries after one invalid field.'],
                    'Design a registration form with at least six controls, labels, grouped choices, browser constraints, and a written plan for server-side errors.'),
            ],
            10 => [
                $this->lesson('Audio Element and Source Selection', 'html-media-audio-source-selection', 'Embed audio with native controls, alternate sources, and a meaningful fallback.', 20,
                    ['Use audio with controls for user-directed playback.', 'Provide source elements for supported formats.', 'Offer a transcript or download fallback.'],
                    'Audio represents sound content in the document. Controls expose familiar playback features, and source children let the browser select a supported encoding. The paragraph fallback is useful when the element is unsupported, while a transcript provides equivalent access to spoken information without listening.',
                    '<figure>\n  <figcaption>Listen to the introduction</figcaption>\n  <audio controls preload="metadata">\n    <source src="intro.ogg" type="audio/ogg">\n    <source src="intro.mp3" type="audio/mpeg">\n    <a href="intro.mp3">Download the audio introduction</a>\n  </audio>\n  <a href="intro-transcript.html">Read the transcript</a>\n</figure>',
                    ['Include controls and a text alternative for spoken content.', 'Declare accurate MIME types for each source.'],
                    ['Do not autoplay audio unexpectedly.', 'Do not offer multiple extensions that actually contain the same unsupported encoding.'],
                    'Mark up a short interview with two audio formats, a caption, and a transcript link.'),
                $this->lesson('Video, Poster, and Playback Controls', 'html-media-video-poster-controls', 'Create a usable video player with dimensions, poster imagery, and user-controlled playback.', 22,
                    ['Embed video with controls and a representative poster.', 'Set intrinsic dimensions for stable layout.', 'Choose loading behavior that respects bandwidth.'],
                    'Video combines moving pictures and usually sound. Controls let users pause, seek, and adjust volume. Poster shows a representative frame before playback, while width and height reserve the media ratio so surrounding content does not jump when the resource loads. Metadata preload can obtain basic media information without eagerly downloading the whole file.',
                    '<video controls width="720" height="405" poster="lesson-preview.jpg" preload="metadata" playsinline>\n  <source src="lesson.mp4" type="video/mp4">\n  <p><a href="lesson-transcript.html">Read the video transcript</a></p>\n</video>',
                    ['Provide stable dimensions and an informative poster.', 'Keep controls available and make transcripts easy to find.'],
                    ['Do not force autoplay with sound.', 'Do not choose dimensions that distort the original aspect ratio.'],
                    'Prepare the markup for a course demonstration video, including poster, dimensions, controls, and a transcript alternative.'),
                $this->lesson('Captions, Subtitles, and Timed Tracks', 'html-media-captions-timed-tracks', 'Attach timed text tracks and distinguish captions from subtitles and descriptions.', 25,
                    ['Use track with kind, src, srclang, and label.', 'Explain why captions include relevant sound information.', 'Test track selection in a browser player.'],
                    'The track element links a WebVTT file to audio or video. Captions convey dialogue and meaningful sound effects for people who cannot hear the program; subtitles commonly translate spoken dialogue. Descriptions can provide visual information. Labels and language metadata make available tracks understandable in player controls.',
                    '<video controls width="640" height="360">\n  <source src="interview.mp4" type="video/mp4">\n  <track kind="captions" src="interview-en.vtt" srclang="en" label="English captions" default>\n  <track kind="subtitles" src="interview-fr.vtt" srclang="fr" label="French subtitles">\n</video>',
                    ['Synchronize captions with speech and meaningful sounds.', 'Identify every track language and purpose accurately.'],
                    ['Do not label translated dialogue as captions if sound cues are omitted.', 'Do not assume the browser can infer track language from a filename.'],
                    'Specify English captions and French subtitles for a short clip and describe what each WebVTT track must contain.'),
                $this->lesson('Media Sources, Formats, and Fallbacks', 'html-media-formats-fallbacks', 'Provide alternate media sources and a useful outcome when no source can play.', 22,
                    ['Use source for alternate encodings.', 'Declare accurate type values.', 'Provide a direct fallback link or transcript.'],
                    'Browsers support media containers and codecs in different combinations. Multiple source elements allow the browser to select a resource it can decode; type can help it skip unsupported candidates. Fallback content inside the media element is not a substitute for testing format support and should tell users how to access the content another way.',
                    '<video controls>\n  <source src="demo.webm" type="video/webm">\n  <source src="demo.mp4" type="video/mp4">\n  <p>Your browser cannot play this video. <a href="demo-transcript.html">Read the transcript</a>.</p>\n</video>',
                    ['Test sources on the actual browser and device targets.', 'Keep transcripts and downloads on stable URLs.'],
                    ['Do not confuse file extensions with actual codecs.', 'Do not leave fallback content as an empty paragraph.'],
                    'Plan alternative audio and video sources for a public course page and describe the fallback for each media item.'),
                $this->lesson('Media Accessibility and Transcripts', 'html-media-accessibility-transcripts', 'Make media understandable through captions, transcripts, descriptions, and accessible controls.', 24,
                    ['Match alternatives to the information carried by media.', 'Provide captions for meaningful audio in video.', 'Use a transcript when spoken content matters.'],
                    'Media accessibility requires equivalent access to information, not merely a player that can be tabbed to. Captions represent speech and relevant sounds, transcripts expose the spoken content as ordinary text, and audio description communicates essential visual events. Native controls should remain keyboard operable and clearly named.',
                    '<figure>\n  <video controls aria-describedby="video-summary">\n    <source src="experiment.mp4" type="video/mp4">\n    <track kind="captions" src="experiment-en.vtt" srclang="en" label="English captions" default>\n  </video>\n  <figcaption id="video-summary">A demonstration of a water filtration experiment.</figcaption>\n  <a href="experiment-transcript.html">Read the full transcript</a>\n</figure>',
                    ['Describe essential visual action that dialogue does not explain.', 'Check caption timing, contrast, and readability.'],
                    ['Do not assume automatic captions are accurate without review.', 'Do not put essential instructions only in an audio track.'],
                    'Create an accessibility checklist for a narrated demonstration with spoken instructions and important visual steps.'),
                $this->lesson('Responsive Media and Loading', 'html-media-responsive-loading', 'Size media responsively and select loading hints that balance performance and quality.', 24,
                    ['Reserve a stable aspect ratio for media.', 'Choose preload and loading hints deliberately.', 'Keep the source quality and responsive display in mind.'],
                    'Media dimensions should match the resource aspect ratio and adapt to the available layout. Intrinsic width and height reserve space, while CSS can scale the display. Preload is a browser hint rather than a guarantee; metadata is often enough for below-the-fold media, while eager loading may suit important above-the-fold content.',
                    '<video controls width="1280" height="720" preload="none" poster="course-preview.jpg">\n  <source src="course-intro.mp4" type="video/mp4">\n</video>\n<img src="diagram-small.jpg" srcset="diagram-small.jpg 480w, diagram-large.jpg 960w" sizes="(max-width: 600px) 100vw, 600px" width="960" height="540" alt="Diagram of the lesson workflow">',
                    ['Set intrinsic dimensions and let presentation adapt to the container.', 'Avoid downloading large media before a user needs it.'],
                    ['Do not stretch media to a different aspect ratio.', 'Do not treat preload as a command that every browser must follow.'],
                    'Choose responsive image candidates and video loading hints for a course landing page viewed on mobile and desktop.'),
                $this->lesson('Embedding Media and External Players', 'html-media-embedding-external-players', 'Embed an external player with an accessible title, privacy awareness, and a fallback.', 23,
                    ['Give an iframe a meaningful title.', 'Use lazy loading for noncritical embeds.', 'Provide an alternative link and consider sandbox restrictions.'],
                    'An iframe embeds a separate browsing context, often used by third-party media players. The title tells users what the frame contains. Loading can be deferred for content below the fold. External players may set cookies, request permissions, or fail, so provide a direct resource link and review privacy and security requirements.',
                    '<section aria-labelledby="talk-title">\n  <h2 id="talk-title">Guest lecture</h2>\n  <iframe src="https://media.example.test/embed/42" title="Guest lecture video player" loading="lazy" allow="fullscreen; picture-in-picture"></iframe>\n  <p><a href="https://media.example.test/watch/42">Open the lecture on the media site</a></p>\n</section>',
                    ['Describe the frame purpose with a unique title.', 'Review provider permissions and third-party data behavior.'],
                    ['Do not embed untrusted pages without a security review.', 'Do not leave essential lecture content available only through the external player.'],
                    'Evaluate an external video embed and propose its title, fallback, loading behavior, and user privacy notice.'),
                $this->lesson('Media Project: A Complete Lesson Player', 'html-media-complete-lesson-player', 'Combine video, captions, transcript, responsive dimensions, and a resilient fallback.', 30,
                    ['Plan the media information and its alternatives.', 'Combine video, source, and timed text markup.', 'Review keyboard use, performance, and fallback behavior.'],
                    'A production-ready media section places the player in context: a heading explains its purpose, the poster previews it, tracks provide captions, and a transcript remains available independently. The page should still communicate the lesson if playback is unsupported or delayed. Test controls, focus order, caption selection, and the visual layout at narrow widths.',
                    '<section aria-labelledby="lesson-video-title">\n  <h2 id="lesson-video-title">How a rain garden works</h2>\n  <video controls width="1280" height="720" poster="rain-garden.jpg" preload="metadata">\n    <source src="rain-garden.mp4" type="video/mp4">\n    <track kind="captions" src="rain-garden-en.vtt" srclang="en" label="English captions" default>\n    <p><a href="rain-garden-transcript.html">Read the transcript</a></p>\n  </video>\n  <p><a href="rain-garden-transcript.html">Open the complete transcript</a></p>\n</section>',
                    ['Keep the transcript available outside the player fallback.', 'Check video ratio, captions, focus, and data use on real devices.'],
                    ['Do not duplicate or omit alternatives when media is embedded.', 'Do not publish a track file without confirming its timing and language.'],
                    'Build a media lesson section for a short instructional clip and submit a checklist covering captions, transcript, fallback, and performance.'),
            ],
            8 => [
                $this->lesson('Landmarks: Header, Nav, Main, and Footer', 'html-semantics-page-landmarks', 'Create recognizable page landmarks and label multiple navigation regions.', 22,
                    ['Mark page header, main content, navigation, and footer.', 'Use one primary main region for the document.', 'Label navigation landmarks when there are several.'],
                    'Landmark elements provide shortcuts through the large regions of a page. Header and footer can apply to the page or a section; nav identifies a significant navigation region; main marks the dominant page content. Multiple nav regions should have distinct accessible names so users can choose the right set of links.',
                    '<header><a href="/">Northside Library</a></header>\n<nav aria-label="Primary navigation"><a href="/events">Events</a><a href="/catalog">Catalog</a></nav>\n<main><h1>Upcoming events</h1><p>Find a reading group or workshop.</p></main>\n<footer><nav aria-label="Footer navigation"><a href="/accessibility">Accessibility</a></nav></footer>',
                    ['Keep the DOM order aligned with reading order.', 'Give repeated landmark types unique labels.'],
                    ['Do not wrap minor link groups in nav without a navigation purpose.', 'Do not place multiple unrelated main elements in one page.'],
                    'Map the landmarks for a library page with primary navigation, in-page navigation, main content, and policy links.'),
                $this->lesson('Sections, Articles, and Asides', 'html-semantics-sections-articles-asides', 'Choose sectioning elements according to thematic grouping and content independence.', 23,
                    ['Use section for a themed group with a heading.', 'Use article for self-contained content.', 'Use aside for related supporting information.'],
                    'Section introduces a thematic part of a document and normally has a heading. Article is appropriate when content can be understood and reused independently, such as a post or announcement. Aside holds supporting information related to nearby content but not essential to its primary flow. These distinctions describe editorial relationships, not visual card shapes.',
                    '<main><h1>Community journal</h1><section><h2>Latest reports</h2><article><h3>New walking path opens</h3><p>The riverside path is now accessible from the east gate.</p></article></section><aside><h2>Related</h2><a href="/maps">Trail map</a></aside></main>',
                    ['Give sections headings that name their subject.', 'Use article for content that has a coherent standalone identity.'],
                    ['Do not use section as a generic styling wrapper.', 'Do not move required instructions into aside merely to visually separate them.'],
                    'Classify article summaries, related links, and thematic page regions for a neighborhood news page.'),
                $this->lesson('Heading Order and Reading Structure', 'html-semantics-heading-order-reading', 'Build a navigable heading outline that reflects the page hierarchy.', 21,
                    ['Create a coherent h1-to-subheading outline.', 'Keep headings descriptive and concise.', 'Check that visual order and DOM order agree.'],
                    'Headings let readers preview a page and let assistive technology jump between sections. The level signals nesting: h2 headings divide the main topic, and h3 headings subdivide an h2. A good outline can be understood without styles and should follow the logical reading sequence presented to users.',
                    '<main><h1>Volunteer Handbook</h1><section><h2>Before your shift</h2><h3>Check in</h3><p>Sign in at the welcome desk.</p><h3>Prepare materials</h3><p>Collect the supplies listed for your activity.</p></section><section><h2>During your shift</h2><p>Ask a coordinator when priorities change.</p></section></main>',
                    ['Use unique, useful headings rather than repeated vague labels.', 'Check the outline in source order and at narrow viewport sizes.'],
                    ['Do not skip from h2 to h5 to achieve a smaller font.', 'Do not use headings for text that is not a section title.'],
                    'Repair a handbook outline with skipped levels and vague headings, then justify the new hierarchy.'),
                $this->lesson('Accessible Links and Images', 'html-semantics-accessible-links-images', 'Make links and images understandable when encountered outside their surrounding layout.', 23,
                    ['Write link names that communicate their destination.', 'Provide purposeful alternatives for informative images.', 'Use empty alt for decorative images.'],
                    'Assistive technology can present links and images in lists without surrounding prose. Link text should identify the destination or action. Alternative text should convey the information relevant to the page task rather than mechanically describe every visible detail. A decorative image can use alt="" so it does not add noise.',
                    '<p>Compare options in the <a href="/plans">membership plan guide</a>.</p>\n<figure><img src="accessible-ramp.jpg" alt="A gently sloped ramp leading to the west entrance" width="720" height="420"><figcaption>Step-free access is available at the west entrance.</figcaption></figure>\n<img src="flourish.svg" alt="">',
                    ['Review image alternatives in context with captions and nearby text.', 'Make each link understandable when read on its own.'],
                    ['Avoid generic link text such as more or here.', 'Do not omit alt on informative images or describe decorative flourishes aloud.'],
                    'Audit five links and three images on a page, rewriting names and alternatives so each purpose is clear.'),
                $this->lesson('Accessible Tables and Data', 'html-semantics-accessible-tables-data', 'Expose table relationships using captions, header cells, and scope.', 24,
                    ['Use tables only for relational data.', 'Add caption and header cells.', 'Associate row and column labels with scope.'],
                    'A data table is a two-dimensional relationship between headers and values. Caption supplies a table name; thead and tbody clarify groups; th identifies a header; scope associates a header with a row or column. For a complex table, consider simpler tables or explicit header identifiers so relationships remain navigable.',
                    '<table>\n  <caption>Library opening hours</caption>\n  <thead><tr><th scope="col">Day</th><th scope="col">Opens</th><th scope="col">Closes</th></tr></thead>\n  <tbody><tr><th scope="row">Monday</th><td>09:00</td><td>18:00</td></tr><tr><th scope="row">Tuesday</th><td>09:00</td><td>20:00</td></tr></tbody>\n</table>',
                    ['Keep tables simple and identify every row or column.', 'Provide a summary nearby when relationships are complex.'],
                    ['Do not use table markup to position unrelated content.', 'Do not use td where a row or column heading is needed.'],
                    'Turn a weekly schedule into an accessible table with a caption, days as row headers, and clearly labeled time columns.'),
                $this->lesson('Forms, Labels, and Error Semantics', 'html-semantics-accessible-form-labels-errors', 'Structure form controls so labels, instructions, groups, and errors are programmatically connected.', 25,
                    ['Associate every control with a label.', 'Group related choices with fieldset and legend.', 'Connect help or error text to its field.'],
                    'A control needs an accessible name, commonly provided by label. Fieldset and legend give context to related choices. Help and error messages should be nearby and connected with aria-describedby when needed. Required status and error state need text or programmatic communication rather than color alone.',
                    '<fieldset><legend>Delivery method</legend><label><input type="radio" name="delivery" value="pickup" required> Pick up in store</label><label><input type="radio" name="delivery" value="ship"> Ship to address</label></fieldset>\n<label for="postal">Postal code</label><input id="postal" name="postal" aria-describedby="postal-help postal-error" required><p id="postal-help">Use the code for your delivery address.</p><p id="postal-error" role="status">Enter a valid postal code.</p>',
                    ['Keep instructions available before and during entry.', 'Make error messages specific and connected to affected controls.'],
                    ['Do not use placeholder as the only control name.', 'Do not indicate invalidity only with red borders or icons.'],
                    'Design the accessible structure and error relationships for a delivery form with address fields and a delivery choice.'),
                $this->lesson('ARIA and Native HTML Semantics', 'html-semantics-aria-native-html', 'Use native HTML first and add ARIA only when it communicates a necessary custom state.', 26,
                    ['Explain when native HTML already supplies semantics.', 'Use labels and state attributes consistently.', 'Keep dynamic ARIA state synchronized with the UI.'],
                    'ARIA changes the accessibility information exposed by an element but does not add browser behavior such as keyboard handling or focus management. A native button is usually better than a clickable div because it already supports keyboard interaction. For custom disclosure controls, aria-expanded must reflect the visible state and aria-controls can identify the affected region.',
                    '<button type="button" aria-expanded="false" aria-controls="shipping-details">Shipping details</button>\n<section id="shipping-details" hidden><h2>Shipping details</h2><p>Orders ship within two working days.</p></section>',
                    ['Prefer native buttons, inputs, and links.', 'Test keyboard behavior and verify that announced state matches visible state.'],
                    ['Do not add redundant roles to native controls.', 'Do not use ARIA attributes as a substitute for implementing interaction behavior.'],
                    'Review a custom disclosure mockup and specify its native element, keyboard behavior, expanded state, and controlled region.'),
                $this->lesson('Accessibility Audit and Page Build', 'html-semantics-accessibility-audit-project', 'Apply semantic structure and an accessibility review to a complete informational page.', 30,
                    ['Combine landmarks and a logical heading structure.', 'Check names and alternatives for links, images, and controls.', 'Test the page with keyboard-only navigation.'],
                    'An accessibility review begins with meaningful HTML and verifies the experience using more than automated scans. Inspect the outline, landmark names, link purpose, image alternatives, form labels, focus order, and zoom behavior. Record issues by user impact and verify each correction in the rendered page and accessibility tree.',
                    '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Accessible Workshop</title></head><body><header><nav aria-label="Primary">...</nav></header><main><h1>Accessible workshop</h1><section><h2>Schedule</h2>...</section><section><h2>Register</h2><form>...</form></section></main><footer>...</footer></body></html>',
                    ['Test with keyboard, zoom, and at least one screen-reader workflow.', 'Fix the source semantics rather than layering visual workarounds.'],
                    ['Do not claim accessibility from an automated score alone.', 'Do not remove visible focus indicators without an equivalent replacement.'],
                    'Build a workshop page and submit an audit checklist for landmarks, heading order, image alternatives, forms, keyboard flow, and zoom.'),
            ],
            11 => [
                $this->lesson('Document Head and Metadata Strategy', 'html-advanced-head-metadata-strategy', 'Organize document metadata for encoding, responsive display, search descriptions, and ownership.', 24,
                    ['Order essential metadata near the start of head.', 'Write a unique title and description.', 'Add a canonical link when duplicate URLs exist.'],
                    'The head communicates document identity and rendering hints. Character encoding should be declared early; viewport metadata supports responsive layouts; title identifies the page in tabs and search results; description summarizes the visible content. Canonical URLs indicate a preferred address when equivalent content can be reached through several paths.',
                    '<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>HTML Structure Guide | LearnWeb</title>\n  <meta name="description" content="A practical guide to semantic HTML page structure.">\n  <link rel="canonical" href="https://learnweb.example/guides/html-structure">\n</head>',
                    ['Make metadata accurate, unique, and consistent with page content.', 'Confirm that canonical URLs use the intended public origin.'],
                    ['Do not duplicate the same title and description across unrelated pages.', 'Do not expect metadata to compensate for thin or confusing visible content.'],
                    'Write the head for a course article with a specific title, summary, viewport, encoding, and preferred URL.'),
                $this->lesson('Responsive and Progressive Metadata', 'html-advanced-responsive-progressive-metadata', 'Set viewport and theme hints while designing pages that remain useful without enhancement.', 22,
                    ['Use viewport metadata for device-width layouts.', 'Understand theme-color as a browser hint.', 'Preserve a working document without optional scripts.'],
                    'Viewport metadata tells mobile browsers to use the device width rather than a wide virtual canvas. Theme-color can suggest browser chrome color, but it does not control page appearance. Progressive enhancement begins with useful semantic content and links, then adds optional behaviors without making the document inaccessible when scripts or external resources fail.',
                    '<meta name="viewport" content="width=device-width, initial-scale=1">\n<meta name="theme-color" content="#14566b">\n<main><h1>Trail conditions</h1><p>All listed paths were checked this morning.</p><a href="/trails/map">View the printable trail map</a></main>',
                    ['Keep essential content in the document itself.', 'Test at narrow widths and with browser text zoom.'],
                    ['Do not disable user zoom with restrictive viewport settings.', 'Do not treat browser chrome hints as a replacement for page colors or contrast.'],
                    'Prepare responsive metadata and a useful no-script page outline for a trail conditions service.'),
                $this->lesson('Custom Data Attributes and Safe Values', 'html-advanced-data-attributes', 'Use data attributes as small public hooks for progressive enhancement.', 20,
                    ['Name custom attributes with the data- prefix.', 'Read data only as public, untrusted input.', 'Prefer semantic attributes when HTML already provides a meaning.'],
                    'The data-* family attaches custom strings to an element and is exposed through the DOM dataset API. It can connect a control to a non-sensitive identifier or enhancement behavior. Data attributes are part of the delivered markup and can be inspected or edited by users, so authorization and trusted values belong on the server.',
                    '<button type="button" data-action="expand" data-panel-id="hours-panel" aria-controls="hours-panel" aria-expanded="false">Show hours</button>\n<section id="hours-panel" hidden><h2>Opening hours</h2><p>Monday to Friday, 9 AM to 5 PM.</p></section>',
                    ['Keep data names stable and specific.', 'Use native href, type, and value attributes when they express the relationship.'],
                    ['Do not store API secrets, permissions, or trusted prices in data attributes.', 'Do not treat an attribute as a substitute for keyboard interaction or accessible state.'],
                    'Specify the public data hooks needed for a collapsible schedule and identify which state still needs to be managed by the application.'),
                $this->lesson('Templates and Repeated Content Structure', 'html-advanced-template-element', 'Define inert reusable markup with template and keep repeated content meaningful.', 23,
                    ['Understand that template content is not rendered by default.', 'Give repeated content a stable semantic structure.', 'Plan an accessible fallback for script-generated items.'],
                    'The template element stores a fragment that scripts can clone later. Its content is inert until inserted into the document. Templates can reduce duplicated client-side markup, but they do not fetch data or create an accessible experience by themselves. A page should preserve a useful initial state and ensure inserted controls receive labels, names, and focus behavior.',
                    '<template id="event-card">\n  <article class="event-card">\n    <h2></h2>\n    <p></p>\n    <a>View event</a>\n  </article>\n</template>\n<div id="events" aria-live="polite"><p>Choose a date to load events.</p></div>',
                    ['Keep the template structure complete and semantic.', 'Provide status feedback when content is inserted asynchronously.'],
                    ['Do not expect template content to appear without script insertion.', 'Do not create repeated headings with no relationship to their containing page.'],
                    'Design a reusable event item template and describe the accessible loading, empty, and populated states around it.'),
                $this->lesson('Iframes, Sandbox, and Embed Boundaries', 'html-advanced-iframe-sandbox', 'Contain embedded documents with a title, deliberate permissions, and useful fallback.', 26,
                    ['Name an iframe with title.', 'Choose sandbox permissions based on required behavior.', 'Provide a direct link when an embed cannot load.'],
                    'An iframe loads a separate document with its own navigation and scripts. Sandbox starts with restrictive behavior and individual permissions can be added only when necessary. The title gives the frame an accessible name. External content introduces privacy, security, performance, and availability considerations that should be documented.',
                    '<section aria-labelledby="schedule-heading">\n  <h2 id="schedule-heading">Live schedule</h2>\n  <iframe src="/public-schedule" title="Public workshop schedule" sandbox="allow-scripts" loading="lazy" width="800" height="500"></iframe>\n  <p><a href="/public-schedule">Open the schedule as a page</a></p>\n</section>',
                    ['Add only the iframe permissions the integration requires.', 'Explain embedded content and preserve a normal link fallback.'],
                    ['Do not combine powerful sandbox permissions without reviewing the trust boundary.', 'Do not let a frame become the only route to essential information.'],
                    'Evaluate an embedded scheduling widget and specify its title, sandbox requirements, loading policy, and non-embedded alternative.'),
                $this->lesson('Details, Summary, and Native Disclosure', 'html-advanced-details-summary', 'Build a browser-native disclosure for optional content with a clear summary label.', 20,
                    ['Use summary as the first child of details.', 'Write a summary that communicates the hidden content.', 'Decide whether the content should start open.'],
                    'Details creates a disclosure widget and summary provides its interactive label. The browser supplies basic keyboard behavior and expanded state, making it simpler and more robust than a custom clickable container. Keep the summary understandable on its own and avoid hiding information users need to complete the primary task.',
                    '<details>\n  <summary>Shipping and returns</summary>\n  <p>Orders ship within two working days. Unused items can be returned within 30 days.</p>\n</details>\n<details open>\n  <summary>Workshop materials</summary>\n  <p>Bring a notebook; all other supplies are provided.</p>\n</details>',
                    ['Use the native element when a simple disclosure is sufficient.', 'Test keyboard activation and the expanded indicator.'],
                    ['Do not put a non-interactive heading before summary inside details.', 'Do not hide critical terms in an unlabeled disclosure.'],
                    'Create three disclosures for a course FAQ and ensure each summary clearly identifies the information it reveals.'),
                $this->lesson('Script Loading and Document Lifecycle', 'html-advanced-script-loading', 'Place scripts with loading attributes that preserve parsing and predictable behavior.', 25,
                    ['Compare deferred and asynchronous scripts.', 'Understand module script defaults.', 'Keep content useful if optional JavaScript fails.'],
                    'A classic script without a loading attribute pauses HTML parsing while it downloads and executes. Defer downloads in parallel and runs after parsing, in document order; async runs as soon as available and is best for independent scripts. Module scripts are deferred by default. The choice affects execution order and when the script can query document content.',
                    '<script src="/assets/navigation.js" defer></script>\n<script src="/assets/metrics.js" async></script>\n<script type="module" src="/assets/course-page.js"></script>',
                    ['Use defer when scripts depend on document order.', 'Load optional independent scripts without blocking essential content.'],
                    ['Do not use async for scripts that require a preceding script to execute first.', 'Do not depend on a script running before the markup it reads exists.'],
                    'Choose a loading strategy for an ordered UI script, an independent analytics script, and a module that enhances lesson markup.'),
                $this->lesson('Advanced Structure Integration Project', 'html-advanced-structure-integration-project', 'Design a robust document combining metadata, semantic regions, disclosures, and external content.', 30,
                    ['Plan the document outline and navigation.', 'Combine metadata, semantics, and progressive enhancement.', 'Document embed and script failure states.'],
                    'A complex page should still be a coherent document before any optional widgets are considered. Start with metadata and landmarks, establish a navigable heading outline, keep related articles together, and use disclosures for optional detail. Add external content and scripts only with clear permissions, loading behavior, and nonessential failure fallbacks.',
                    '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Research Field Guide</title><script type="module" src="/assets/guide.js"></script></head><body><header>...</header><main><h1>Research field guide</h1><article><section><h2>Methods</h2>...</section><details><summary>Equipment notes</summary>...</details></article><aside>...</aside></main><footer>...</footer></body></html>',
                    ['Build and validate semantic content before testing optional behavior.', 'Keep every external dependency named and explainable.'],
                    ['Do not add structure solely for visual layout.', 'Do not let optional scripts or embeds prevent access to the main document.'],
                    'Plan a research guide with metadata, landmarks, two articles, a disclosure, one external embed, and a written fallback for each dependency.'),
            ],
            12 => [
                $this->lesson('Plan a Page Around User Tasks', 'html-view-pages-plan-user-tasks', 'Turn an audience and page goal into a clear information outline before writing markup.', 20,
                    ['Identify the audience and primary task.', 'List information required to complete that task.', 'Create a heading outline before implementation.'],
                    'A real page starts with the reader rather than a list of tags. Define what visitors need to know or do, prioritize primary and supporting information, and sketch the page outline. This plan influences which regions, headings, links, media, and form controls will be appropriate.',
                    '<main>\n  <h1>Repair cafe</h1>\n  <section><h2>What we repair</h2><p>Small household items and clothing.</p></section>\n  <section><h2>When to visit</h2><p>First Saturday of each month.</p></section>\n  <section><h2>Book a place</h2>...</section>\n</main>',
                    ['Write the page purpose in one sentence.', 'Prioritize information based on the reader journey.'],
                    ['Do not begin with visual decoration before deciding the content hierarchy.', 'Do not make every section equally prominent when tasks differ in importance.'],
                    'Write a brief and content outline for a local service page, including the main visitor task and supporting questions.'),
                $this->lesson('Shared Site Header and Branding', 'html-view-pages-shared-header-branding', 'Create a recognizable header that identifies the site and introduces its main navigation.', 21,
                    ['Represent branding as useful text or a link.', 'Group primary navigation in a labeled nav landmark.', 'Keep header source order logical.'],
                    'A site header provides identity and orientation. A brand link commonly returns to the home page; a concise tagline can explain the service; a primary navigation group lists a few high-value destinations. The header should not become a catch-all for every utility action, especially on small screens.',
                    '<header>\n  <a href="/" aria-label="Harbor Learning home"><strong>Harbor Learning</strong></a>\n  <p>Practical classes for curious people</p>\n  <nav aria-label="Primary navigation"><a href="/classes">Classes</a><a href="/calendar">Calendar</a><a href="/about">About</a></nav>\n</header>',
                    ['Use consistent header markup across related pages.', 'Make each navigation destination clear and reachable.'],
                    ['Do not make a logo image the only accessible name for the site.', 'Do not include a duplicate, unlabeled copy of the primary menu.'],
                    'Build a shared header for three connected pages and explain how users identify the brand and reach the key sections.'),
                $this->lesson('Navigation Between Pages and Sections', 'html-view-pages-navigation', 'Connect a small site with useful page links and in-page anchors.', 22,
                    ['Use URLs that match the page or section destination.', 'Add stable ids for in-page navigation.', 'Indicate current page where appropriate.'],
                    'Multi-page navigation links to documents; in-page navigation links to fragments whose ids occur in the current document. A table of contents is useful on long pages when its targets have stable, descriptive ids. aria-current="page" can identify the active page in a navigation set.',
                    '<nav aria-label="Primary navigation"><a href="index.html">Home</a><a href="services.html" aria-current="page">Services</a><a href="contact.html">Contact</a></nav>\n<nav aria-label="On this page"><a href="#consulting">Consulting</a><a href="#training">Training</a></nav>\n<section id="consulting"><h2>Consulting</h2><p>...</p></section>\n<section id="training"><h2>Training</h2><p>...</p></section>',
                    ['Test links from every page and ensure fragment ids are unique.', 'Use current-page state only where the destination actually matches.'],
                    ['Do not use buttons for ordinary URL navigation.', 'Do not use unstable numeric fragments that break after content edits.'],
                    'Create primary navigation for a three-page site and in-page navigation for a long services page.'),
                $this->lesson('Landing Page Introduction and Hero Content', 'html-view-pages-landing-introduction', 'Write a focused page introduction with a meaningful heading and purposeful next action.', 22,
                    ['Use a heading that names the page offer or topic.', 'Pair supporting context with a useful next step.', 'Keep essential meaning in actual document content.'],
                    'A prominent introduction is a content region, not a special HTML element. Its heading should state the page topic or offer directly; supporting text explains the audience or outcome; links take users to related content while buttons trigger actions. An image can reinforce the message but should not contain information absent from text.',
                    '<main><section aria-labelledby="intro-title"><h1 id="intro-title">Learn to repair everyday objects</h1><p>Join a guided workshop, bring one item, and leave with practical skills.</p><p><a href="#schedule">View workshop dates</a> <a href="/register">Reserve a place</a></p></section><section id="schedule"><h2>Next workshop</h2>...</section></main>',
                    ['Make the heading specific and the next action explicit.', 'Keep important content available as selectable text.'],
                    ['Do not create competing page introductions with unrelated headings.', 'Do not rely on a background image to explain the offer.'],
                    'Write an introduction for a community class that states the offer, audience benefit, and a clear path to dates or registration.'),
                $this->lesson('Content Sections and Reusable Cards', 'html-view-pages-content-sections-cards', 'Structure repeated services or features consistently inside a meaningful section.', 24,
                    ['Give a collection a descriptive section heading.', 'Use article for independent repeated items where appropriate.', 'Keep repeated item structure consistent.'],
                    'A list of services or features needs an introduction and consistent item-level information. Article fits an item that has a meaningful standalone identity; list elements fit a simple collection. The important choice is the relationship between items and the surrounding topic, not whether the design uses cards or borders.',
                    '<section aria-labelledby="classes-title"><h2 id="classes-title">Choose a class</h2><article><h3>Woodworking basics</h3><p>Learn safe measuring, joining, and finishing.</p><a href="/classes/woodworking">See class details</a></article><article><h3>Textile mending</h3><p>Practice visible and invisible repairs.</p><a href="/classes/mending">See class details</a></article></section>',
                    ['Give each repeated item the same essential content pattern.', 'Use links that name the specific destination.'],
                    ['Do not use article for every visually boxed element automatically.', 'Do not repeat generic links whose destination is unclear.'],
                    'Mark up three course offerings with a shared title, summary, and destination, then explain whether each is an article or list item.'),
                $this->lesson('Contact Details and Inquiry Forms', 'html-view-pages-contact-details-forms', 'Provide direct contact methods alongside a labeled inquiry form.', 25,
                    ['Use address, mailto, and tel where appropriate.', 'Label form controls and state response expectations.', 'Collect only information needed to respond.'],
                    'A contact page can provide a physical address, hours, direct email and phone links, and a form. The address element groups contact information for the relevant organization. Form labels should remain visible, required status should be explicit, and the page should tell users what happens after submission.',
                    '<section aria-labelledby="contact-title"><h2 id="contact-title">Contact the studio</h2><address>18 Cedar Lane<br>Riverside</address><p><a href="mailto:hello@studio.example">Email the studio</a></p><p><a href="tel:+15550186">Call 555-0186</a></p><form action="/inquiries" method="post"><label for="contact-email">Your email</label><input id="contact-email" name="email" type="email" required><label for="question">How can we help?</label><textarea id="question" name="question" rows="5" required></textarea><button type="submit">Send inquiry</button></form></section>',
                    ['Explain how and when a response will arrive.', 'Use labels, validation, and a useful success state.'],
                    ['Do not request sensitive details without a clear need.', 'Do not provide a form with no submission feedback or privacy context.'],
                    'Build a contact section with address, business hours, direct contact links, and a two-field inquiry form.'),
                $this->lesson('Footer, Policies, and Secondary Navigation', 'html-view-pages-footer-secondary-navigation', 'Finish a web page with helpful secondary links and clear organization details.', 20,
                    ['Group secondary links by user purpose.', 'Use a footer landmark for closing page information.', 'Keep legal and accessibility information discoverable.'],
                    'The footer gives the page a predictable ending and can include contact details, policy links, organization ownership, or a secondary navigation. If there are several groups, short headings or labeled nav regions explain them. Footer structure should remain useful on every viewport and should not duplicate the entire primary menu without purpose.',
                    '<footer><nav aria-label="Company information"><a href="/about">About</a><a href="/contact">Contact</a></nav><nav aria-label="Policies"><a href="/privacy">Privacy</a><a href="/accessibility">Accessibility</a></nav><p>© 2026 Harbor Learning</p></footer>',
                    ['Keep labels consistent across pages.', 'Check keyboard access and link contrast in the footer.'],
                    ['Do not hide essential support links in an unlabeled dense list.', 'Do not leave stale copyright years or broken routes.'],
                    'Create a reusable footer for a small business site with company, support, and policy destinations.'),
                $this->lesson('Complete Multi-Page Website Project', 'html-view-pages-complete-website-project', 'Combine page planning, navigation, accessible content, contact details, and consistent shared regions.', 30,
                    ['Design a small site map with distinct page purposes.', 'Reuse header and footer patterns while keeping page content unique.', 'Audit the complete site for links and semantic structure.'],
                    'A complete website is a set of documents with shared identity and clear differences in purpose. Define a site map, create a unique title and h1 for every page, reuse shared navigation, and keep each main region focused. Finish by following every link, checking language and headings, reviewing media alternatives, and testing the interaction order with a keyboard.',
                    '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Harbor Learning | Home</title></head><body><header><a href="index.html">Harbor Learning</a><nav aria-label="Primary"><a href="classes.html">Classes</a><a href="about.html">About</a><a href="contact.html">Contact</a></nav></header><main><h1>Build practical skills together</h1><section><h2>Upcoming classes</h2>...</section></main><footer>...</footer></body></html>',
                    ['Give every page a distinct title, heading, and purpose.', 'Test the complete navigation graph rather than isolated pages.'],
                    ['Do not leave placeholder links or duplicate page titles.', 'Do not treat a successful visual render as the only quality check.'],
                    'Plan and implement a four-page site for a local learning center, then submit a page map and review checklist for semantics, navigation, accessibility, and content completeness.'),
            ],
        ];
    }

    private function lesson(
        string $title,
        string $slug,
        string $description,
        int $minutes,
        array $objectives,
        string $explanation,
        string $example,
        array $bestPractices,
        array $pitfalls,
        string $practice
    ): array {
        return compact('title', 'slug', 'description', 'minutes', 'objectives', 'explanation', 'example', 'bestPractices', 'pitfalls', 'practice') + [
            'best_practices' => $bestPractices,
        ];
    }
}