name: Build macOS Installer

on:
  push:
    tags:
      - "v*"

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs

      - name: Install NPM dependencies
        run: npm install

      - name: Build frontend asset
        run: npm run build

      - name: Build macOS Application
        run: php artisan native:build mac --no-interaction

      - name: Upload macOS Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg-installer
          path: nativephp/electron/dist/*.dmg
